Repository sopt-makers/sopt-android, pull requests merged in 2023-04, with the labels that each got.

#147 [feature/#111] Implement SOPT Design System
  app/src/main/java/org/sopt/official/feature/notice/components/NoticeItem.kt
  app/src/main/res/drawable/ic_attendance.xml
  app/src/main/res/drawable/ic_bell.xml
  app/src/main/res/drawable/ic_crew.xml
  app/src/main/res/drawable/ic_faq.xml
  app/src/main/res/drawable/ic_homepage.xml
  app/src/main/res/drawable/ic_member.xml
  app/src/main/res/drawable/ic_mypage.xml
  app/src/main/res/drawable/ic_new.xml
  app/src/main/res/drawable/ic_notice.xml
  app/src/main/res/drawable/ic_project.xml
  app/src/main/res/drawable/ic_review.xml
  app/src/main/res/drawable/ic_youtube.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/themes.xml
  app/src/main/res/values/type.xml
Labels: size/L

#148 :lipstick: Theme, type file update
  app/src/main/res/values/themes.xml
  app/src/main/res/values/type.xml
Labels: size/M

#139 feat: 운영서비스 - 출석 점수 조회 기능 구현
  .github/workflows/develop_PR_builder.yml
  .github/workflows/develop_merge_builder.yml
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/sopt/official/MainActivity.kt
  app/src/main/java/org/sopt/official/data/model/attendance/AttendanceHistoryResponse.kt
  app/src/main/java/org/sopt/official/data/model/attendance/BaseAttendanceResponse.kt
  app/src/main/java/org/sopt/official/data/model/attendance/SoptEventResponse.kt
  app/src/main/java/org/sopt/official/data/repository/attendance/AttendanceRepositoryImpl.kt
  app/src/main/java/org/sopt/official/data/service/attendance/AttendanceService.kt
  app/src/main/java/org/sopt/official/data/service/attendance/MockAttendanceService.kt
  app/src/main/java/org/sopt/official/di/AuthModule.kt
  app/src/main/java/org/sopt/official/di/NetModule.kt
  app/src/main/java/org/sopt/official/di/annotation/Interceptor.kt
  app/src/main/java/org/sopt/official/di/attendance/AttendanceBindsModule.kt
  app/src/main/java/org/sopt/official/domain/entity/attendance/AttendanceHistory.kt
  app/src/main/java/org/sopt/official/domain/entity/attendance/AttendanceLog.kt
  app/src/main/java/org/sopt/official/domain/entity/attendance/AttendanceStatus.kt
  app/src/main/java/org/sopt/official/domain/entity/attendance/AttendanceSummary.kt
  app/src/main/java/org/sopt/official/domain/entity/attendance/AttendanceUserInfo.kt
  app/src/main/java/org/sopt/official/domain/entity/attendance/EventAttribute.kt
  app/src/main/java/org/sopt/official/domain/entity/attendance/EventType.kt
  app/src/main/java/org/sopt/official/domain/entity/attendance/Part.kt
  app/src/main/java/org/sopt/official/domain/entity/attendance/SoptEvent.kt
  app/src/main/java/org/sopt/official/domain/repository/attendance/AttendanceRepository.kt
  app/src/main/java/org/sopt/official/feature/attendance/AttendanceActivity.kt
  app/src/main/java/org/sopt/official/feature/attendance/AttendanceViewModel.kt
  app/src/main/java/org/sopt/official/feature/attendance/adapter/AttendanceAdapter.kt
  app/src/main/java/org/sopt/official/feature/attendance/adapter/LogHeaderViewHolder.kt
  app/src/main/java/org/sopt/official/feature/attendance/adapter/LogViewHolder.kt
  app/src/main/java/org/sopt/official/feature/attendance/adapter/SummaryViewHolder.kt
  app/src/main/java/org/sopt/official/feature/attendance/adapter/UserInfoViewHolder.kt
  app/src/main/java/org/sopt/official/feature/attendance/model/AttendanceState.kt
  app/src/main/java/org/sopt/official/feature/attendance/util/NumberExtensions.kt
  app/src/main/res/drawable/ic_attendance_arrow_left_white.xml
  app/src/main/res/drawable/ic_attendance_event_date.xml
  app/src/main/res/drawable/ic_attendance_event_location.xml
  app/src/main/res/drawable/ic_attendance_point_info.xml
  app/src/main/res/drawable/ic_refresh.xml
  app/src/main/res/drawable/rectangle_radius_16.xml
  app/src/main/res/drawable/rectangle_radius_4.xml
  app/src/main/res/drawable/rectangle_radius_8.xml
  app/src/main/res/layout/activity_attendance.xml
  app/src/main/res/layout/item_attendance_history_log.xml
  app/src/main/res/layout/item_attendance_history_log_header.xml
  app/src/main/res/layout/item_attendance_history_summary.xml
  app/src/main/res/layout/item_attendance_history_user_info.xml
  app/src/main/res/menu/menu_attendance_overview.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
  build-logic/convention/src/main/kotlin/org/sopt/official/plugin/CommonConfigs.kt
Labels: size/XXL

#156 솝트 앱 비즈니스 로직 & API 연결. #129
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/sopt/official/MainActivity.kt
  app/src/main/java/org/sopt/official/base/BaseItemType.kt
  app/src/main/java/org/sopt/official/data/model/main/MainView.kt
  app/src/main/java/org/sopt/official/data/repository/main/MainViewRepositoryImpl.kt
  app/src/main/java/org/sopt/official/data/service/main/MainViewService.kt
  app/src/main/java/org/sopt/official/di/MainViewModule.kt
  app/src/main/java/org/sopt/official/domain/entity/UserState.kt
  app/src/main/java/org/sopt/official/domain/entity/main/MainView.kt
  app/src/main/java/org/sopt/official/domain/repository/main/MainViewRepository.kt
  app/src/main/java/org/sopt/official/feature/auth/AuthActivity.kt
  app/src/main/java/org/sopt/official/feature/auth/AuthViewModel.kt
  app/src/main/java/org/sopt/official/feature/main/MainActivity.kt
  app/src/main/java/org/sopt/official/feature/main/MainViewModel.kt
  app/src/main/java/org/sopt/official/feature/web/WebUrlConstant.kt
  app/src/main/java/org/sopt/official/util/GenerationExt.kt
  app/src/main/java/org/sopt/official/util/coroutine/FlowExt.kt
  app/src/main/java/org/sopt/official/util/ui/ViewExt.kt
  app/src/main/java/org/sopt/official/util/wrapper/NullableExt.kt
  app/src/main/res/drawable/img_logo.xml
  app/src/main/res/layout/activity_sopt_main.xml
  app/src/main/res/layout/item_main_content.xml
  app/src/main/res/layout/item_main_large.xml
  app/src/main/res/layout/item_main_small_block_list.xml
  app/src/main/res/values/strings.xml
Labels: size/XL

#155 솝트 메인화면 디자인 ui 구성
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/sopt/official/MainActivity.kt
  app/src/main/java/org/sopt/official/base/BaseAdapter.kt
  app/src/main/java/org/sopt/official/base/BaseItemType.kt
  app/src/main/java/org/sopt/official/base/BaseViewHolder.kt
  app/src/main/java/org/sopt/official/data/model/main/MainView.kt
  app/src/main/java/org/sopt/official/data/repository/main/MainViewRepositoryImpl.kt
  app/src/main/java/org/sopt/official/data/service/main/MainViewService.kt
  app/src/main/java/org/sopt/official/di/MainViewModule.kt
  app/src/main/java/org/sopt/official/domain/entity/UserState.kt
  app/src/main/java/org/sopt/official/domain/entity/main/MainView.kt
  app/src/main/java/org/sopt/official/domain/repository/main/MainViewRepository.kt
  app/src/main/java/org/sopt/official/feature/auth/AuthActivity.kt
  app/src/main/java/org/sopt/official/feature/auth/AuthViewModel.kt
  app/src/main/java/org/sopt/official/feature/main/MainActivity.kt
  app/src/main/java/org/sopt/official/feature/main/MainViewModel.kt
  app/src/main/java/org/sopt/official/feature/web/WebUrlConstant.kt
  app/src/main/java/org/sopt/official/util/DifferConfigCompat.kt
  app/src/main/java/org/sopt/official/util/GenerationExt.kt
  app/src/main/java/org/sopt/official/util/coroutine/FlowExt.kt
  app/src/main/java/org/sopt/official/util/ui/ViewExt.kt
  app/src/main/java/org/sopt/official/util/wrapper/NullableExt.kt
  app/src/main/res/color/selector_member_tag_state.xml
  app/src/main/res/drawable/ic_mypage.xml
  app/src/main/res/drawable/img_soptamp.xml
  app/src/main/res/drawable/oval.xml
  app/src/main/res/drawable/rectangle_radius_15.xml
  app/src/main/res/layout/activity_sopt_main.xml
  app/src/main/res/layout/item_main_content.xml
  app/src/main/res/layout/item_main_content_member_header.xml
  app/src/main/res/layout/item_main_content_non_member_header.xml
  app/src/main/res/layout/item_main_large.xml
  app/src/main/res/layout/item_main_member_generation.xml
  app/src/main/res/layout/item_main_small.xml
  app/src/main/res/layout/item_main_small_block_list.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: size/XXL

#164 :bug: pgauth 버전 올리고 로그인 실패 시 비회원으로 메인 진입할 수 있게 수정
  app/src/main/java/org/sopt/official/feature/auth/AuthActivity.kt
  app/src/main/java/org/sopt/official/feature/main/MainActivity.kt
  app/src/main/res/layout/activity_auth.xml
  gradle/libs.versions.toml
Labels: size/S

#165 [feature/home-logo-change] 메인 화면 로고 변경
  app/src/main/res/drawable-hdpi/img_logo_small.png
  app/src/main/res/drawable-xhdpi/img_logo_small.png
  app/src/main/res/drawable-xxhdpi/img_logo_small.png
  app/src/main/res/drawable-xxxhdpi/img_logo_small.png
  app/src/main/res/drawable/img_logo_small.png
  app/src/main/res/layout/activity_sopt_main.xml
Labels: size/XS

#163 코드 리팩토링 - user state 가져오는 부분과 collect
  app/src/main/java/org/sopt/official/feature/main/MainActivity.kt
  app/src/main/java/org/sopt/official/feature/main/MainViewModel.kt
  app/src/main/java/org/sopt/official/util/Intent.kt
  app/src/main/java/org/sopt/official/util/Resource.kt
  app/src/main/java/org/sopt/official/util/coroutine/FlowExt.kt
  app/src/main/res/layout/activity_sopt_main.xml
  app/src/main/res/layout/item_main_content_member_header.xml
  app/src/main/res/values/strings.xml
Labels: size/XL

#167 ➕ PGAuth 0.1.5 -> 0.1.6
  gradle/libs.versions.toml
Labels: size/XS

#172 [운영서비스] 출석 점수 조회 QA 반영
  app/src/main/java/org/sopt/official/data/service/attendance/AttendanceService.kt
  app/src/main/java/org/sopt/official/di/NetModule.kt
  app/src/main/java/org/sopt/official/feature/attendance/AttendanceActivity.kt
  app/src/main/java/org/sopt/official/feature/attendance/adapter/AttendanceAdapter.kt
  app/src/main/java/org/sopt/official/feature/attendance/adapter/SummaryViewHolder.kt
  app/src/main/res/anim/anim_rotation.xml
  app/src/main/res/layout/activity_attendance.xml
  app/src/main/res/layout/item_attendance_history_log.xml
Labels: size/M

#171 운영서비스 - 출석 기능 구현
  app/src/main/java/org/sopt/official/data/model/attendance/AttendanceCodeResponse.kt
  app/src/main/java/org/sopt/official/data/model/attendance/AttendanceRoundResponse.kt
  app/src/main/java/org/sopt/official/data/model/attendance/BaseAttendanceResponse.kt
  app/src/main/java/org/sopt/official/data/model/attendance/RequestAttendanceCode.kt
  app/src/main/java/org/sopt/official/data/model/attendance/SoptEventResponse.kt
  app/src/main/java/org/sopt/official/data/repository/attendance/AttendanceRepositoryImpl.kt
  app/src/main/java/org/sopt/official/data/service/attendance/AttendanceService.kt
  app/src/main/java/org/sopt/official/data/service/attendance/MockAttendanceService.kt
  app/src/main/java/org/sopt/official/domain/entity/attendance/AttendanceButtonType.kt
  app/src/main/java/org/sopt/official/domain/entity/attendance/AttendanceErrorCode.kt
  app/src/main/java/org/sopt/official/domain/entity/attendance/AttendanceRound.kt
  app/src/main/java/org/sopt/official/domain/repository/attendance/AttendanceRepository.kt
  app/src/main/java/org/sopt/official/feature/attendance/AttendanceActivity.kt
  app/src/main/java/org/sopt/official/feature/attendance/AttendanceCodeDialog.kt
  app/src/main/java/org/sopt/official/feature/attendance/AttendanceViewModel.kt
  app/src/main/java/org/sopt/official/feature/attendance/CustomTextWatcher.kt
  app/src/main/java/org/sopt/official/feature/attendance/model/DialogState.kt
  app/src/main/res/color/attendance_button.xml
  app/src/main/res/color/attendance_button_text.xml
  app/src/main/res/color/attendance_progress_text.xml
  app/src/main/res/drawable/ic_attendance_check.xml
  app/src/main/res/drawable/ic_close.xml
  app/src/main/res/drawable/ic_point.xml
  app/src/main/res/drawable/oval_border_gray40.xml
  app/src/main/res/drawable/oval_fill_purpledim100_border_purple40.xml
  app/src/main/res/drawable/oval_fill_white_border_purple40.xml
  app/src/main/res/drawable/rectangle_black40_radius_8.xml
  app/src/main/res/drawable/rectangle_border_purple_radius_8.xml
  app/src/main/res/drawable/rectangle_radius_10.xml
  app/src/main/res/drawable/rectangle_radius_6.xml
  app/src/main/res/drawable/selector_edittext_attendance_code.xml
  app/src/main/res/layout/activity_attendance.xml
  app/src/main/res/layout/dialog_attendance_code.xml
  app/src/main/res/values/strings.xml
  core/src/main/java/org/sopt/official/core/di/Toast.kt
Labels: size/XXL

#174 [feature/seunghyeon/spr1/qa2] SPR1 운영팀 QA
  app/src/main/java/org/sopt/official/data/model/attendance/SoptEventResponse.kt
  app/src/main/java/org/sopt/official/data/repository/attendance/AttendanceRepositoryImpl.kt
  app/src/main/java/org/sopt/official/feature/attendance/AttendanceActivity.kt
  app/src/main/java/org/sopt/official/feature/attendance/AttendanceCodeDialog.kt
  app/src/main/java/org/sopt/official/feature/attendance/AttendanceViewModel.kt
  app/src/main/res/layout/activity_attendance.xml
Labels: size/M

#176 솝탬프에서 상대 미션 리스트 안보이던 문제 해결
  feature/soptamp/src/main/java/org/sopt/official/stamp/designsystem/component/mission/MissionComponent.kt
  feature/soptamp/src/main/java/org/sopt/official/stamp/domain/model/OtherMission.kt
  feature/soptamp/src/main/java/org/sopt/official/stamp/feature/mission/MissionsState.kt
  feature/soptamp/src/main/java/org/sopt/official/stamp/feature/mission/MissionsViewModel.kt
  feature/soptamp/src/main/java/org/sopt/official/stamp/feature/mission/list/MissionListScreen.kt
  feature/soptamp/src/main/java/org/sopt/official/stamp/feature/mission/list/UserMissionListScreen.kt
  feature/soptamp/src/main/java/org/sopt/official/stamp/feature/mission/model/MissionListUiModel.kt
  feature/soptamp/src/main/java/org/sopt/official/stamp/feature/mission/model/MissionNavArgs.kt
  feature/soptamp/src/main/java/org/sopt/official/stamp/feature/mission/model/MissionUiModel.kt
Labels: size/L

#170 마이페이지
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/sopt/official/data/persistence/SoptDataStore.kt
  app/src/main/java/org/sopt/official/data/repository/AuthRepositoryImpl.kt
  app/src/main/java/org/sopt/official/designsystem/AlertDialogPositiveNegative.kt
  app/src/main/java/org/sopt/official/domain/repository/AuthRepository.kt
  app/src/main/java/org/sopt/official/feature/main/MainActivity.kt
  app/src/main/java/org/sopt/official/feature/mypage/MyPageActivity.kt
  app/src/main/java/org/sopt/official/feature/mypage/MyPageViewModel.kt
  app/src/main/java/org/sopt/official/feature/mypage/signOut/SignOutActivity.kt
  app/src/main/java/org/sopt/official/feature/mypage/signOut/SignOutViewModel.kt
  app/src/main/java/org/sopt/official/feature/mypage/soptamp/nickName/ChangeNickNameActivity.kt
  app/src/main/java/org/sopt/official/feature/mypage/soptamp/nickName/ChangeNickNameViewModel.kt
  app/src/main/java/org/sopt/official/feature/mypage/soptamp/sentence/AdjustSentenceActivity.kt
  app/src/main/java/org/sopt/official/feature/mypage/soptamp/sentence/AdjustSentenceViewModel.kt
  app/src/main/java/org/sopt/official/feature/web/WebUrlConstant.kt
  app/src/main/res/color/selector_button_enable.xml
  app/src/main/res/color/selector_edit_text_background.xml
  app/src/main/res/color/selector_edit_text_border.xml
  app/src/main/res/drawable/btn_arrow_left.xml
  app/src/main/res/drawable/btn_arrow_right.xml
  app/src/main/res/drawable/layout_edit_text_background.xml
  app/src/main/res/drawable/layout_edit_text_error_background.xml
  app/src/main/res/drawable/rectangle_radius_12.xml
  app/src/main/res/layout/activity_adjust_sentence.xml
  app/src/main/res/layout/activity_change_nick_name.xml
  app/src/main/res/layout/activity_my_page.xml
  app/src/main/res/layout/activity_sign_out.xml
  app/src/main/res/layout/layout_dialog_negative_positive.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
  feature/soptamp/src/main/java/org/sopt/official/stamp/data/remote/api/StampService.kt
  feature/soptamp/src/main/java/org/sopt/official/stamp/data/repository/UserRepositoryImpl.kt
  feature/soptamp/src/main/java/org/sopt/official/stamp/domain/fake/FakeUserRepository.kt
  feature/soptamp/src/main/java/org/sopt/official/stamp/domain/repository/UserRepository.kt
Labels: size/XXL

#177 [feature/readme] SOPT 앱 리드미 추가
  .all-contributorsrc
  README.md
Labels: size/L

#181 Badge 부분 리드미 수정
  README.md
Labels: size/XS

#185 이슈 통해서 버그 제보할 수 있게 설정 [skip ci]
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: size/S

#184 [feature/nunu/soptamp-fix] SOPTAMP 쪽 이슈 잡기
  app/src/main/java/org/sopt/official/data/persistence/SoptDataStore.kt
  app/src/main/java/org/sopt/official/feature/main/MainActivity.kt
  feature/soptamp/src/main/java/org/sopt/official/stamp/data/remote/api/StampService.kt
  feature/soptamp/src/main/java/org/sopt/official/stamp/data/repository/StampRepositoryImpl.kt
  feature/soptamp/src/main/java/org/sopt/official/stamp/designsystem/component/layout/Layout.kt
  feature/soptamp/src/main/java/org/sopt/official/stamp/domain/fake/FakeStampRepository.kt
  feature/soptamp/src/main/java/org/sopt/official/stamp/domain/repository/StampRepository.kt
  feature/soptamp/src/main/java/org/sopt/official/stamp/feature/mission/MissionsViewModel.kt
  feature/soptamp/src/main/java/org/sopt/official/stamp/feature/mission/detail/MissionDetail.kt
  feature/soptamp/src/main/java/org/sopt/official/stamp/feature/mission/detail/MissionDetailViewModel.kt
  feature/soptamp/src/main/java/org/sopt/official/stamp/feature/mission/list/MissionListScreen.kt
  feature/soptamp/src/main/java/org/sopt/official/stamp/feature/mission/list/UserMissionListScreen.kt
  feature/soptamp/src/main/java/org/sopt/official/stamp/feature/onboarding/OnboardingPage.kt
  feature/soptamp/src/main/java/org/sopt/official/stamp/feature/onboarding/OnboardingScreen.kt
  feature/soptamp/src/main/java/org/sopt/official/stamp/feature/onboarding/PagingIndicator.kt
  feature/soptamp/src/main/java/org/sopt/official/stamp/feature/ranking/RankingState.kt
  feature/soptamp/src/main/java/org/sopt/official/stamp/feature/ranking/RankingViewModel.kt
  feature/soptamp/src/main/res/drawable/ic_soptamp_guide.xml
Labels: size/L

#186 운영서비스 출석기능 QA
  app/src/main/java/org/sopt/official/data/model/attendance/AttendanceCodeResponse.kt
  app/src/main/java/org/sopt/official/data/repository/attendance/AttendanceRepositoryImpl.kt
  app/src/main/java/org/sopt/official/domain/entity/attendance/AttendanceButtonType.kt
  app/src/main/java/org/sopt/official/domain/entity/attendance/AttendanceRound.kt
  app/src/test/java/org/sopt/official/ExampleUnitTest.kt
  app/src/test/java/org/sopt/official/JsonObjectTest.kt
Labels: size/L
