Repository sopt-makers/sopt-android, pull requests merged in 2023-10, with the labels that each got.

#378 [bug/soptamp_design] 솝템프 랭킹 플로팅 버튼 디자인 수정
  feature/soptamp/src/main/java/org/sopt/official/stamp/designsystem/component/button/SoptampSegmentedFloatingButton.kt
Labels: bug, size/S

#390 [feature/refresh-token] 토큰 자동 갱신 로직 추가 및 자동 로그인 기능 추가
  app/src/main/java/org/sopt/official/data/authenticator/SoptAuthenticator.kt
  app/src/main/java/org/sopt/official/data/repository/AuthRepositoryImpl.kt
  app/src/main/java/org/sopt/official/di/AuthModule.kt
  app/src/main/java/org/sopt/official/di/HomeModule.kt
  app/src/main/java/org/sopt/official/di/NetModule.kt
  app/src/main/java/org/sopt/official/feature/auth/AuthActivity.kt
  app/src/main/java/org/sopt/official/feature/home/HomeActivity.kt
  core/common/src/main/java/org/sopt/official/common/di/Qualifiers.kt
  feature/auth/build.gradle.kts
  feature/auth/src/main/java/org/sopt/official/auth/data/RemotePlaygroundAuthDatasource.kt
  feature/soptamp/src/main/java/org/sopt/official/stamp/di/RemoteModule.kt
Labels: size/L

#393 [Feature/#391] 알림 내역 버튼에 amplitude 적용
  app/src/main/java/org/sopt/official/feature/home/HomeActivity.kt
Labels: size/XS

#394 [feature/fix-dependencies] 뷰모델/도메인단 코드 리팩토링
  app/src/main/java/org/sopt/official/data/repository/AuthRepositoryImpl.kt
  app/src/main/java/org/sopt/official/data/source/api/.gitkeep
  app/src/main/java/org/sopt/official/data/source/api/auth/LocalAuthDataSource.kt
  app/src/main/java/org/sopt/official/data/source/api/auth/RemoteAuthDataSource.kt
  app/src/main/java/org/sopt/official/data/source/impl/.gitkeep
  app/src/main/java/org/sopt/official/data/source/impl/DefaultLocalAuthDataSource.kt
  app/src/main/java/org/sopt/official/data/source/impl/DefaultRemoteAuthDataSource.kt
  app/src/main/java/org/sopt/official/di/AuthModule.kt
  app/src/main/java/org/sopt/official/domain/repository/AuthRepository.kt
  app/src/main/java/org/sopt/official/feature/home/HomeViewModel.kt
  app/src/main/java/org/sopt/official/feature/mypage/MyPageViewModel.kt
Labels: size/L

#371 [feature/remove-databinding] Data Binding 라이브러리와 kapt 플러그인 제거
  app/build.gradle.kts
  app/src/main/java/org/sopt/official/feature/attendance/AttendanceActivity.kt
  app/src/main/java/org/sopt/official/feature/attendance/AttendanceCodeDialog.kt
  app/src/main/java/org/sopt/official/feature/attendance/AttendanceViewModel.kt
  app/src/main/java/org/sopt/official/util/Resource.kt
  app/src/main/res/layout/activity_attendance.xml
  app/src/main/res/layout/dialog_attendance_code.xml
  build-logic/convention/src/main/kotlin/org/sopt/official/plugin/CommonConfigs.kt
  build.gradle.kts
  core/common/src/main/java/org/sopt/official/common/lifecycle/FragmentLifecycleOwner.kt
  core/common/src/main/java/org/sopt/official/common/lifecycle/LiveData.kt
  feature/soptamp/src/main/java/org/sopt/official/stamp/feature/mission/detail/MissionDetailViewModel.kt
  gradle/libs.versions.toml
Labels: size/XXL
