Repository sopt-makers/sopt-android, pull requests merged in 2023-09, with the labels that each got.

#311 [feature/object-to-data-object] Refactor object to data object
  app/src/main/java/org/sopt/official/feature/attendance/model/AttendanceState.kt
  app/src/main/java/org/sopt/official/feature/attendance/model/DialogState.kt
  app/src/main/java/org/sopt/official/feature/main/MainViewModel.kt
  feature/soptamp/src/main/java/org/sopt/official/stamp/data/error/ErrorData.kt
  feature/soptamp/src/main/java/org/sopt/official/stamp/domain/error/Error.kt
  feature/soptamp/src/main/java/org/sopt/official/stamp/feature/mission/MissionsState.kt
  feature/soptamp/src/main/java/org/sopt/official/stamp/feature/ranking/RankingState.kt
Labels: size/S

#316 [feature/separate-dev-release] 빌드 환경 dev와 release로 구분하기
  .gitignore
  app/build.gradle.kts
  app/src/debug/res/drawable/ic_launcher_foreground.xml
  app/src/debug/res/drawable/ic_launcher_foreground_copy.xml
  app/src/debug/res/drawable/ic_launcher_foreground_debug.xml
  app/src/debug/res/values/strings.xml
  gradlew.bat
  keystore/debug.keystore
Labels: enhancement, size/L

#317 [feature/version-bump] Kotlin version bump
  gradle/libs.versions.toml
Labels: size/XS

#325 [feature/login-issue] 로그인시 잠재적으로 발생할 수 있는 이슈 해소
  .github/workflows/develop_PR_builder.yml
  .github/workflows/develop_merge_builder.yml
  app/build.gradle.kts
  app/src/main/java/org/sopt/official/App.kt
  app/src/main/java/org/sopt/official/config/messaging/SoptFirebaseMessagingService.kt
  app/src/main/java/org/sopt/official/data/model/request/AuthRequest.kt
  app/src/main/java/org/sopt/official/data/model/response/AuthResponse.kt
  app/src/main/java/org/sopt/official/data/persistence/SoptDataStore.kt
  app/src/main/java/org/sopt/official/feature/auth/AuthActivity.kt
  app/src/main/java/org/sopt/official/feature/main/MainActivity.kt
  app/src/main/java/org/sopt/official/util/Auth.kt
  build-logic/convention/src/main/kotlin/org/sopt/official/plugin/CommonConfigs.kt
  build-logic/settings.gradle.kts
  feature/auth/.gitignore
  feature/auth/build.gradle.kts
  feature/auth/consumer-rules.pro
  feature/auth/src/main/AndroidManifest.xml
  feature/auth/src/main/java/org/sopt/official/auth/AuthCodeHandlerActivity.kt
  feature/auth/src/main/java/org/sopt/official/auth/AuthIntentFactory.kt
  feature/auth/src/main/java/org/sopt/official/auth/AuthStateGenerator.kt
  feature/auth/src/main/java/org/sopt/official/auth/Constants.kt
  feature/auth/src/main/java/org/sopt/official/auth/DefaultAuthStateGenerator.kt
  feature/auth/src/main/java/org/sopt/official/auth/PlaygroundAuth.kt
  feature/auth/src/main/java/org/sopt/official/auth/PlaygroundAuthResultReceiver.kt
  feature/auth/src/main/java/org/sopt/official/auth/PlaygroundError.kt
  feature/auth/src/main/java/org/sopt/official/auth/PlaygroundInfo.kt
  feature/auth/src/main/java/org/sopt/official/auth/PlaygroundResultReceiver.kt
  feature/auth/src/main/java/org/sopt/official/auth/data/PlaygroundApiManager.kt
  feature/auth/src/main/java/org/sopt/official/auth/data/PlaygroundAuthDatasource.kt
  feature/auth/src/main/java/org/sopt/official/auth/data/RemotePlaygroundAuthDatasource.kt
  feature/auth/src/main/java/org/sopt/official/auth/data/remote/AuthService.kt
  feature/auth/src/main/java/org/sopt/official/auth/data/remote/ServiceFactory.kt
  feature/auth/src/main/java/org/sopt/official/auth/data/remote/model/request/RequestToken.kt
  feature/auth/src/main/java/org/sopt/official/auth/data/remote/model/response/OauthToken.kt
  feature/auth/src/main/java/org/sopt/official/auth/utils/BundleExt.kt
  feature/auth/src/main/java/org/sopt/official/auth/utils/PlaygroundCustomTabManager.kt
  feature/auth/src/main/java/org/sopt/official/auth/utils/PlaygroundHttpLoggingInterceptor.kt
  feature/auth/src/main/java/org/sopt/official/auth/utils/PlaygroundLog.kt
  feature/auth/src/main/java/org/sopt/official/auth/utils/PlaygroundUriProvider.kt
  feature/soptamp/build.gradle.kts
  gradle/libs.versions.toml
  settings.gradle.kts
Labels: size/XL

#329 [feature/hilt-ksp] Apply ksp on hilt
  app/build.gradle.kts
  build-logic/convention/src/main/kotlin/org/sopt/official/plugin/AndroidHiltPlugin.kt
  feature/soptamp/src/main/java/org/sopt/official/stamp/di/ConfigModule.kt
  feature/soptamp/src/main/java/org/sopt/official/stamp/di/ConstantModule.kt
  feature/soptamp/src/main/java/org/sopt/official/stamp/di/constant/Constant.kt
  gradle/libs.versions.toml
Labels: size/S

#326 [김다혜] Pair, Triple -> Data Class 전환
  .gitignore
  app/src/main/java/org/sopt/official/domain/entity/main/MainView.kt
  app/src/main/java/org/sopt/official/feature/main/MainViewModel.kt
  feature/soptamp/src/main/java/org/sopt/official/stamp/feature/ranking/TopRankerList.kt
  feature/soptamp/src/main/java/org/sopt/official/stamp/feature/ranking/model/RankersUiModel.kt
  feature/soptamp/src/main/java/org/sopt/official/stamp/feature/ranking/model/RankingListUiModel.kt
Labels: size/L

#335 Manifest에 AuthCodeHandlerActivity 추가
  app/src/main/AndroidManifest.xml
Labels: bug, size/S

#337 Add firebase app distribution
  app/build.gradle.kts
  build.gradle.kts
  gradle/libs.versions.toml
Labels: size/XS

#343 [feature/customtab-issue-fix] Custom Tab issue fix
  app/src/main/AndroidManifest.xml
Labels: size/S

#348 운영 서비스 - 출석 리팩토링
  app/src/main/java/org/sopt/official/data/service/attendance/MockAttendanceService.kt
  app/src/main/java/org/sopt/official/domain/entity/attendance/AttendanceButtonType.kt
  app/src/main/java/org/sopt/official/feature/attendance/AttendanceActivity.kt
  app/src/main/java/org/sopt/official/feature/attendance/AttendanceViewModel.kt
Labels: size/L

#351 [Chore/#350] 마이페이지 - 의견 보내기 구글 폼 링크 연결
  app/src/main/java/org/sopt/official/feature/mypage/MyPageActivity.kt
  app/src/main/java/org/sopt/official/feature/web/WebUrlConstant.kt
Labels: size/XS

#352 [FEAT] 운영 프로덕트 - 색상 변경하기
  app/src/main/java/org/sopt/official/feature/attendance/adapter/UserInfoViewHolder.kt
  app/src/main/res/color/attendance_button.xml
  app/src/main/res/color/attendance_button_text.xml
  app/src/main/res/drawable/ic_attendacne_check_white.xml
  app/src/main/res/drawable/ic_attendance_check_gray.xml
  app/src/main/res/drawable/ic_point.xml
  app/src/main/res/drawable/oval_fill_black60_border_white100.xml
  app/src/main/res/drawable/oval_fill_white_border_gray60.xml
  app/src/main/res/drawable/rectangle_black40_radius_8.xml
  app/src/main/res/drawable/rectangle_border_gray40_radius_8.xml
  app/src/main/res/drawable/selector_edittext_attendance_code.xml
  app/src/main/res/layout/activity_attendance.xml
  app/src/main/res/layout/dialog_attendance_code.xml
  app/src/main/res/values/colors.xml
Labels: size/L

#358 [feature/fix-soptamp] SOPTAMP 버튼 두짝 달리게 하기
  feature/soptamp/src/main/java/org/sopt/official/stamp/data/remote/api/RankService.kt
  feature/soptamp/src/main/java/org/sopt/official/stamp/data/remote/source/RemoteRankingDataSource.kt
  feature/soptamp/src/main/java/org/sopt/official/stamp/data/repository/RemoteRankingRepository.kt
  feature/soptamp/src/main/java/org/sopt/official/stamp/data/source/RankingDataSource.kt
  feature/soptamp/src/main/java/org/sopt/official/stamp/designsystem/component/button/SoptampFloatingButton.kt
  feature/soptamp/src/main/java/org/sopt/official/stamp/designsystem/component/button/SoptampSegmentedFloatingButton.kt
  feature/soptamp/src/main/java/org/sopt/official/stamp/domain/model/Rank.kt
  feature/soptamp/src/main/java/org/sopt/official/stamp/domain/repository/RankingRepository.kt
  feature/soptamp/src/main/java/org/sopt/official/stamp/feature/mission/list/MissionListScreen.kt
  feature/soptamp/src/main/java/org/sopt/official/stamp/feature/ranking/RankingScreen.kt
  feature/soptamp/src/main/java/org/sopt/official/stamp/feature/ranking/RankingViewModel.kt
Labels: size/L

#361 apply clipToBounds
  feature/soptamp/src/main/java/org/sopt/official/stamp/designsystem/component/button/SoptampSegmentedFloatingButton.kt
Labels: size/XS

#363 [FEAT] 운영 프로덕트 - 출석 기능 고도화
  app/src/main/java/org/sopt/official/feature/attendance/AttendanceActivity.kt
  app/src/main/java/org/sopt/official/feature/attendance/AttendanceViewModel.kt
  app/src/main/res/drawable/ic_attendance_close_gray.xml
  app/src/main/res/drawable/ic_attendance_close_white.xml
  app/src/main/res/layout/activity_attendance.xml
  app/src/main/res/layout/item_attendance_history_summary.xml
Labels: size/L

#354 ktlint-format apply
  app/src/main/java/org/sopt/official/data/model/main/DescriptionViewResponse.kt
  app/src/main/java/org/sopt/official/data/model/main/MainViewResponse.kt
  app/src/main/java/org/sopt/official/data/service/main/MainViewService.kt
  app/src/main/java/org/sopt/official/feature/attendance/AttendanceCodeDialog.kt
  app/src/main/java/org/sopt/official/feature/main/MainViewModel.kt
  feature/soptamp/src/main/java/org/sopt/official/stamp/data/remote/api/RankService.kt
  feature/soptamp/src/main/java/org/sopt/official/stamp/data/remote/model/response/RankDetailResponse.kt
  feature/soptamp/src/main/java/org/sopt/official/stamp/di/ConfigModule.kt
  feature/soptamp/src/main/java/org/sopt/official/stamp/feature/ranking/model/RankerUiModel.kt
Labels: size/S

#367 [feature/refactor-code-structure] 홈쪽 코드 로직 개편
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/sopt/official/base/BaseAdapter.kt
  app/src/main/java/org/sopt/official/base/BaseItemType.kt
  app/src/main/java/org/sopt/official/base/BaseViewHolder.kt
  app/src/main/java/org/sopt/official/data/model/home/DescriptionViewResponse.kt
  app/src/main/java/org/sopt/official/data/model/home/HomeResponse.kt
  app/src/main/java/org/sopt/official/data/model/main/MainViewResponse.kt
  app/src/main/java/org/sopt/official/data/repository/home/DefaultHomeRepository.kt
  app/src/main/java/org/sopt/official/data/repository/main/MainViewRepositoryImpl.kt
  app/src/main/java/org/sopt/official/data/service/home/HomeService.kt
  app/src/main/java/org/sopt/official/data/service/main/MainViewService.kt
  app/src/main/java/org/sopt/official/di/HomeModule.kt
  app/src/main/java/org/sopt/official/domain/entity/UserActiveState.kt
  app/src/main/java/org/sopt/official/domain/entity/auth/UserStatus.kt
  app/src/main/java/org/sopt/official/domain/entity/home/Home.kt
  app/src/main/java/org/sopt/official/domain/entity/main/MainView.kt
  app/src/main/java/org/sopt/official/domain/entity/user/User.kt
  app/src/main/java/org/sopt/official/domain/repository/home/HomeRepository.kt
  app/src/main/java/org/sopt/official/domain/repository/main/MainViewRepository.kt
  app/src/main/java/org/sopt/official/feature/auth/AuthActivity.kt
  app/src/main/java/org/sopt/official/feature/home/HomeActivity.kt
  app/src/main/java/org/sopt/official/feature/home/HomeViewModel.kt
  app/src/main/java/org/sopt/official/feature/home/adapter/SmallBlockAdapter.kt
  app/src/main/java/org/sopt/official/feature/home/model/HomeCTAType.kt
  app/src/main/java/org/sopt/official/feature/home/model/HomeMenuType.kt
  app/src/main/java/org/sopt/official/feature/home/model/SoptMainContentUrl.kt
  app/src/main/java/org/sopt/official/feature/home/model/UserActiveGeneration.kt
  app/src/main/java/org/sopt/official/feature/home/model/UserUiState.kt
  app/src/main/java/org/sopt/official/feature/main/MainActivity.kt
  app/src/main/java/org/sopt/official/feature/main/MainViewModel.kt
  app/src/main/java/org/sopt/official/feature/mypage/MyPageActivity.kt
  app/src/main/java/org/sopt/official/feature/mypage/MyPageViewModel.kt
  app/src/main/java/org/sopt/official/feature/mypage/model/MyPageUiState.kt
  app/src/main/java/org/sopt/official/util/DifferConfigCompat.kt
  app/src/main/java/org/sopt/official/util/Intent.kt
  app/src/main/java/org/sopt/official/util/Resource.kt
  app/src/main/java/org/sopt/official/util/wrapper/NullableExt.kt
  app/src/main/res/layout/activity_my_page.xml
  app/src/main/res/layout/activity_sopt_main.xml
  app/src/main/res/layout/item_main_small.xml
  app/src/main/res/layout/item_main_small_block_list.xml
  app/src/test/java/org/sopt/official/CalculateActiveGenerationTest.kt
  core/src/main/java/org/sopt/official/core/view/ItemDiffCallback.kt
  feature/soptamp/src/main/java/org/sopt/official/stamp/data/remote/api/SoptampUserService.kt
  feature/soptamp/src/main/java/org/sopt/official/stamp/designsystem/component/button/SoptampSegmentedFloatingButton.kt
Labels: size/XXL
