Repository sopt-makers/sopt-android, pull requests merged in 2023-11, with the labels that each got.

#434 [Hotfix/yxnsx/#424] Notification channel 수정
  app/src/main/java/org/sopt/official/feature/auth/AuthActivity.kt
Labels: bug, size/XS

#439 Home 화면 유일하게 띄워놓게 만들기
  app/src/main/java/org/sopt/official/feature/home/HomeActivity.kt
Labels: size/XS

#444 Version bump
  README.md
  build.gradle.kts
  gradle/libs.versions.toml
Labels: size/S

#450 [feature/add-base-webview-client] Add SOPTWebView + WebViewClient
  app/build.gradle.kts
  build-logic/convention/src/main/kotlin/org/sopt/official/plugin/CommonConfigs.kt
  core/webview/.gitignore
  core/webview/build.gradle.kts
  core/webview/consumer-rules.pro
  core/webview/src/main/AndroidManifest.xml
  core/webview/src/main/java/org/sopt/official/webview/di/SoptWebViewEntryPoint.kt
  core/webview/src/main/java/org/sopt/official/webview/view/SoptWebView.kt
  core/webview/src/main/java/org/sopt/official/webview/view/SoptWebViewClient.kt
  settings.gradle.kts
Labels: size/L
