Repository sopt-makers/sopt-android, pull requests merged in 2023-12, with the labels that each got.

#464 [Feature/#463] 홈 메뉴 추가
  app/src/main/java/org/sopt/official/feature/home/HomeViewModel.kt
  app/src/main/java/org/sopt/official/feature/home/model/HomeCTAType.kt
  app/src/main/java/org/sopt/official/feature/home/model/HomeMenuType.kt
  app/src/main/res/drawable/ic_playground_orange.png
  app/src/main/res/values/strings.xml
  feature/mypage/src/main/java/org/sopt/official/feature/mypage/web/WebUrlConstant.kt
Labels: size/M

#487 [Feature/#483] mds 컬러 반영
  app/src/main/res/drawable/ic_attendance_orange.xml
  app/src/main/res/drawable/ic_crew_orange.xml
  app/src/main/res/drawable/ic_homepage_orange.xml
  app/src/main/res/layout/activity_sopt_main.xml
  app/src/main/res/layout/item_main_content.xml
  app/src/main/res/layout/item_main_large.xml
  app/src/main/res/layout/item_main_member_generation.xml
  app/src/main/res/layout/item_main_small.xml
  app/src/main/res/values/strings.xml
  core/designsystem/src/main/java/org/sopt/official/designsystem/Color.kt
  core/designsystem/src/main/java/org/sopt/official/designsystem/Theme.kt
  feature/mypage/src/main/res/drawable/layout_edit_text_error_background.xml
  feature/mypage/src/main/res/layout/activity_my_page.xml
  feature/mypage/src/main/res/values/colors.xml
  feature/soptamp/src/main/java/org/sopt/official/stamp/designsystem/style/Color.kt
  feature/soptamp/src/main/java/org/sopt/official/stamp/designsystem/style/Theme.kt
Labels: size/L

#492 Apply spotless
  core/webview/build.gradle.kts
  core/webview/src/main/AndroidManifest.xml
  core/webview/src/main/java/org/sopt/official/webview/di/SoptWebViewEntryPoint.kt
  core/webview/src/main/java/org/sopt/official/webview/view/SoptWebView.kt
  core/webview/src/main/java/org/sopt/official/webview/view/SoptWebViewClient.kt
  feature/soptamp/src/main/java/org/sopt/official/stamp/designsystem/style/Color.kt
Labels: size/L

#494 [Fix/#493] mds 추가 적용
  app/src/main/res/color/selector_button_state.xml
  app/src/main/res/color/selector_edit_text_border.xml
  app/src/main/res/color/selector_member_tag_state.xml
  app/src/main/res/color/selector_member_tag_text_state.xml
  app/src/main/res/color/selector_notification_filter_chip_background.xml
  app/src/main/res/color/selector_notification_filter_text.xml
  app/src/main/res/drawable/layout_edit_text_error_background.xml
  app/src/main/res/drawable/shape_white100_10.xml
  app/src/main/res/layout/activity_auth.xml
  app/src/main/res/layout/activity_notification_detail.xml
  app/src/main/res/layout/activity_notification_history.xml
  app/src/main/res/layout/activity_sopt_main.xml
  app/src/main/res/layout/item_main_content_member_header.xml
  app/src/main/res/layout/item_main_small.xml
  app/src/main/res/layout/layout_dialog_negative_positive.xml
  core/designsystem/src/main/res/values/colors.xml
  core/designsystem/src/main/res/values/themes.xml
  feature/mypage/src/main/res/color/selector_button_state.xml
  feature/mypage/src/main/res/color/selector_edit_text_border.xml
  feature/mypage/src/main/res/color/selector_notification_filter_chip_background.xml
  feature/mypage/src/main/res/color/selector_notification_filter_text.xml
  feature/mypage/src/main/res/layout/activity_adjust_sentence.xml
  feature/mypage/src/main/res/layout/activity_change_nick_name.xml
  feature/mypage/src/main/res/layout/activity_sign_out.xml
  feature/mypage/src/main/res/layout/layout_dialog_negative_positive.xml
  feature/mypage/src/main/res/values/colors.xml
Labels: size/L

#498 [Hotfix/#497] 홈 > 플레이그라운드 CTA 수정
  app/src/main/java/org/sopt/official/feature/home/model/HomeCTAType.kt
  app/src/main/java/org/sopt/official/feature/home/model/HomeMenuType.kt
  app/src/main/res/drawable/ic_playground_orange.png
  app/src/main/res/values/strings.xml
Labels: size/XS

#499 Bump Kotlin, Jetpack Compose compiler version
  README.md
  gradle/libs.versions.toml
Labels: size/XS

#508 change version reference
  gradle/libs.versions.toml
Labels: size/XS

#520 사용하지 않는 코드 삭제 + Lint Apply
  app/src/main/java/org/sopt/official/di/UpdateModule.kt
  app/src/main/java/org/sopt/official/feature/notification/NotificationDetailActivity.kt
  app/src/main/java/org/sopt/official/feature/notification/SchemeActivity.kt
  app/src/main/java/org/sopt/official/feature/notification/enums/DeepLinkType.kt
  app/src/main/java/org/sopt/official/feature/update/InAppUpdateManager.kt
  app/src/main/java/org/sopt/official/feature/update/InAppUpdateManagerImpl.kt
  app/src/main/java/org/sopt/official/feature/update/UpdateCriteria.kt
  app/src/main/res/layout/activity_notification_detail.xml
  core/common/src/main/java/org/sopt/official/common/util/StringExtraction.kt
  feature/soptamp/src/main/java/org/sopt/official/stamp/feature/setting/nickname/UpdateNicknameViewModel.kt
Labels: size/L
