Repository sopt-makers/sopt-android, pull requests merged in 2023-05, with the labels that each got.

#189 [feature/junit5-configuration] 테스트 라이브러리 JUnit5로 교체
  app/build.gradle.kts
  app/src/test/java/org/sopt/official/JsonObjectTest.kt
  build-logic/convention/build.gradle.kts
  build-logic/convention/src/main/kotlin/org/sopt/official/plugin/JUnit5Plugin.kt
  build.gradle.kts
  gradle/libs.versions.toml
Labels: size/M

#195 Type system: fontweight -> textFontWeight
  app/src/main/res/values/type.xml
Labels: size/S

#205 [feature/nunu/retry-make-shared-preference] SharedPreference 초기화 시 앱 강제 종료되는 이슈 의심 되는 부분 수정
  app/src/main/java/org/sopt/official/data/persistence/SoptDataStore.kt
Labels: size/M

#207 [Feature/kotlinx-datetime]: #204 java-time to kotlinx-datetime migration
  app/src/main/java/org/sopt/official/feature/main/MainViewModel.kt
  app/src/main/java/org/sopt/official/util/GenerationExt.kt
  app/src/main/java/org/sopt/official/util/TimeExt.kt
  app/src/test/java/org/sopt/official/JsonObjectTest.kt
  app/src/test/java/org/sopt/official/KotlinxDateTimeTest.kt
Labels: size/L

#210 [feature/bump-androidx-security] Androidx Security 버전 up
  app/build.gradle.kts
  app/src/main/java/org/sopt/official/data/persistence/SoptDataStore.kt
  app/src/main/java/org/sopt/official/di/SecurityModule.kt
  app/src/test/java/org/sopt/official/datastore/SoptDataStoreTest.kt
  app/src/test/java/org/sopt/official/datastore/fake/FakeAESKeyGenerator.kt
  app/src/test/java/org/sopt/official/datastore/fake/FakeAndroidKeyStore.kt
  app/src/test/java/org/sopt/official/datastore/fake/FakeKeyStore.kt
  build-logic/convention/build.gradle.kts
  build-logic/convention/src/main/kotlin/org/sopt/official/plugin/AndroidHiltPlugin.kt
  build-logic/convention/src/main/kotlin/org/sopt/official/plugin/AndroidTestPlugin.kt
  build-logic/convention/src/main/kotlin/org/sopt/official/plugin/JUnit5Plugin.kt
  core/src/main/java/org/sopt/official/core/di/Qualifiers.kt
  feature/soptamp/src/main/java/org/sopt/official/stamp/di/ConfigModule.kt
  gradle/libs.versions.toml
Labels: size/L

#154 Bump JDK, Kotlin, AGP, Gradle, Compose, Compose-destination, ksp
  .github/workflows/develop_PR_builder.yml
  .github/workflows/develop_merge_builder.yml
  build-logic/convention/build.gradle.kts
  build-logic/convention/src/main/kotlin/org/sopt/official/plugin/AndroidKotlinPlugin.kt
  build-logic/convention/src/main/kotlin/org/sopt/official/plugin/CommonConfigs.kt
  feature/soptamp/src/main/java/org/sopt/official/stamp/feature/mission/detail/MissionDetail.kt
  gradle/libs.versions.toml
Labels: size/M

#214 [Fix/LoggingInterceptor]: #213 loggingInterceptor-leak
  app/src/main/java/org/sopt/official/di/NetModule.kt
Labels: size/XS

#224 [feature/nunu/uiautomator-test] 안드로이드 자동화 테스트 설정
  app/src/androidTest/java/org/sopt/official/AppStartupTest.kt
  app/src/androidTest/java/org/sopt/official/ExampleInstrumentedTest.kt
  build-logic/convention/src/main/kotlin/org/sopt/official/plugin/AndroidTestPlugin.kt
  build-logic/convention/src/main/kotlin/org/sopt/official/plugin/JUnit5Plugin.kt
  gradle/libs.versions.toml
Labels: size/L
