Repository sopt-makers/sopt-android, pull requests merged in 2024-04, with the labels that each got.

#669 [release/2.2.0] 🚨 2.2.0
  gradle/libs.versions.toml
Labels: size/XS

#671 [feature/apply-lifecycle-service] Service에 Lifecycle 적용하기
  app/src/main/java/org/sopt/official/config/messaging/ServiceLifecycleDispatcher.kt
  app/src/main/java/org/sopt/official/config/messaging/SoptFirebaseMessagingService.kt
Labels: size/L

#675 feat: handle OnBackPressed
  core/webview/src/main/java/org/sopt/official/webview/view/WebViewActivity.kt
Labels: size/S
