Repository sopt-makers/sopt-android, pull requests merged in 2024-03, with the labels that each got.

#594 [feature/pure-kotlin-plugin] Apply Pure Kotlin Plugin for build.gradle.kts
  app/build.gradle.kts
  build-logic/convention/build.gradle.kts
  build-logic/convention/src/main/kotlin/org/sopt/official/plugin/KotlinJvmPlugin.kt
  buildSrc/build.gradle.kts
  buildSrc/gradle.properties
  buildSrc/settings.gradle.kts
  buildSrc/src/main/kotlin/sopt.kt
  core/analytics/build.gradle.kts
  core/auth/build.gradle.kts
  core/authimpl/build.gradle.kts
  core/common/build.gradle.kts
  core/designsystem/build.gradle.kts
  core/network/build.gradle.kts
  core/webview/build.gradle.kts
  data/mypage/build.gradle.kts
  data/poke/build.gradle.kts
  data/soptamp/build.gradle.kts
  domain/build.gradle.kts
  domain/mypage/build.gradle.kts
  domain/poke/build.gradle.kts
  domain/soptamp/build.gradle.kts
  feature/auth/build.gradle.kts
  feature/mypage/build.gradle.kts
  feature/poke/build.gradle.kts
  feature/soptamp/build.gradle.kts
Labels: size/L

#595 [feature/makers-design-system] Makers Design System (Current Version)
  core/designsystem/build.gradle.kts
  core/designsystem/src/main/java/org/sopt/official/designsystem/Color.kt
  core/designsystem/src/main/java/org/sopt/official/designsystem/Theme.kt
  core/designsystem/src/main/java/org/sopt/official/designsystem/Type.kt
  core/designsystem/src/main/res/font/pretendard_bold.otf
  core/designsystem/src/main/res/font/pretendard_light.otf
  core/designsystem/src/main/res/font/pretendard_medium.otf
  core/designsystem/src/main/res/font/pretendard_regular.otf
  core/designsystem/src/main/res/font/pretendard_semibold.otf
  core/designsystem/src/test/java/org/sopt/official/designsystem/ColorTest.kt
Labels: size/XL

#601 Update README.md
  README.md
Labels: size/XS

#608 Feature 이슈 템플릿 생성
  .github/ISSUE_TEMPLATE/feature-issue-template.md
Labels: size/S

#621 Bump Compose version and fix test build
  gradle/libs.versions.toml
Labels: size/XS

#626 [docs] Change Kotlin version 1.9.22 -> 1.9.23
  README.md
Labels: size/XS

#629 Remove domain module build script
  core/authimpl/build.gradle.kts
  domain/build.gradle.kts
Labels: size/M

#630 [feature/replace-deprecated-methods] Remove deprecated methods & fix lint, warnings
  app/src/main/java/org/sopt/official/data/service/notification/NotificationService.kt
  core/common/src/main/java/org/sopt/official/common/di/Qualifiers.kt
  core/common/src/main/java/org/sopt/official/common/util/Intent.kt
  feature/auth/src/main/java/org/sopt/official/auth/AuthCodeHandlerActivity.kt
  feature/auth/src/main/java/org/sopt/official/auth/PlaygroundAuthResultReceiver.kt
  feature/auth/src/main/java/org/sopt/official/auth/utils/BundleExt.kt
  feature/poke/src/main/java/org/sopt/official/feature/poke/friend/summary/FriendListSummaryActivity.kt
  feature/poke/src/main/java/org/sopt/official/feature/poke/friend/summary/FriendListSummaryViewModel.kt
  feature/poke/src/main/java/org/sopt/official/feature/poke/main/PokeMainActivity.kt
  feature/poke/src/main/java/org/sopt/official/feature/poke/main/PokeMainViewModel.kt
  feature/poke/src/main/java/org/sopt/official/feature/poke/message/MessageListBottomSheetFragment.kt
  feature/poke/src/main/java/org/sopt/official/feature/poke/message/MessageListRecyclerAdapter.kt
  feature/poke/src/main/java/org/sopt/official/feature/poke/notification/PokeNotificationActivity.kt
  feature/poke/src/main/java/org/sopt/official/feature/poke/notification/PokeNotificationAdapter.kt
  feature/poke/src/main/java/org/sopt/official/feature/poke/notification/PokeNotificationViewModel.kt
  feature/poke/src/main/java/org/sopt/official/feature/poke/onboarding/OnboardingActivity.kt
  feature/poke/src/main/java/org/sopt/official/feature/poke/onboarding/OnboardingBottomSheetFragment.kt
  feature/poke/src/main/java/org/sopt/official/feature/poke/onboarding/OnboardingViewModel.kt
  feature/poke/src/main/java/org/sopt/official/feature/poke/user/ItemDecorationDivider.kt
  feature/poke/src/main/java/org/sopt/official/feature/poke/user/PokeUserListAdapter.kt
  feature/soptamp/src/main/java/org/sopt/official/stamp/feature/mission/MissionsViewModel.kt
  feature/soptamp/src/main/java/org/sopt/official/stamp/feature/mission/detail/component/Memo.kt
  gradle.properties
  gradle/libs.versions.toml
Labels: size/L

#634 Update license file
  LICENSE
Labels: size/XS

#636 [featuer/soptamp-toolcahin] add Kotlin jvmToolchain
  build-logic/convention/build.gradle.kts
Labels: size/XS

#646 [hotfix/contact with kakao] 문의하기 링크 google -> kakao
  build-logic/convention/build.gradle.kts
  feature/mypage/src/main/java/org/sopt/official/feature/mypage/mypage/MyPageActivity.kt
  feature/mypage/src/main/java/org/sopt/official/feature/mypage/web/WebUrlConstant.kt
  feature/mypage/src/main/res/layout/activity_my_page.xml
Labels: size/L
