Repository sopt-makers/sopt-android, pull requests merged in 2024-10, with the labels that each got.

#876 [Feature/#875] fortune amulet TodayFortuneCard API
  domain/fortune/src/main/java/org/sopt/official/domain/fortune/usecase/GetTodayFortuneCardUseCase.kt
  feature/fortune/src/main/java/org/sopt/official/feature/fortune/FortuneActivity.kt
  feature/fortune/src/main/java/org/sopt/official/feature/fortune/FoundationScreen.kt
  feature/fortune/src/main/java/org/sopt/official/feature/fortune/feature/fortuneAmulet/FortuneAmuletScreen.kt
  feature/fortune/src/main/java/org/sopt/official/feature/fortune/feature/fortuneAmulet/FortuneAmuletState.kt
  feature/fortune/src/main/java/org/sopt/official/feature/fortune/feature/fortuneAmulet/FortuneAmuletViewModel.kt
  feature/fortune/src/main/java/org/sopt/official/feature/fortune/feature/fortuneAmulet/navigation/FortuneAmuletNavGraph.kt
  feature/fortune/src/main/java/org/sopt/official/feature/fortune/feature/fortuneDetail/component/TodayFortuneDashboard.kt
  feature/fortune/src/main/java/org/sopt/official/feature/fortune/feature/home/HomeScreen.kt
  feature/fortune/src/main/java/org/sopt/official/feature/fortune/feature/home/navigation/HomeNavGraph.kt
Labels: size/L

#910 [Feature/#908] 오늘의 솝마디 앰플리튜드 & NDS & 에러뷰 적용
  app/src/release/generated/baselineProfiles/baseline-prof.txt
  app/src/release/generated/baselineProfiles/startup-prof.txt
  data/soptamp/src/main/java/org/sopt/official/data/soptamp/remote/api/SoptampService.kt
  data/soptamp/src/main/java/org/sopt/official/data/soptamp/remote/mapper/MissionStatusMapper.kt
  data/soptamp/src/main/java/org/sopt/official/data/soptamp/remote/model/response/MissionStatusResponse.kt
  data/soptamp/src/main/java/org/sopt/official/data/soptamp/remote/model/response/ReportUrlResponse.kt
  data/soptamp/src/main/java/org/sopt/official/data/soptamp/source/MissionsDataSource.kt
  feature/fortune/src/androidTest/java/org/sopt/official/feature/fortune/fortuneDetail/FortuneDetailScreenTest.kt
  feature/fortune/src/main/java/org/sopt/official/feature/fortune/FortuneActivity.kt
  feature/fortune/src/main/java/org/sopt/official/feature/fortune/component/FortuneTopBar.kt
  feature/fortune/src/main/java/org/sopt/official/feature/fortune/feature/fortuneAmulet/FortuneAmuletScreen.kt
  feature/fortune/src/main/java/org/sopt/official/feature/fortune/feature/fortuneAmulet/navigation/FortuneAmuletNavGraph.kt
  feature/fortune/src/main/java/org/sopt/official/feature/fortune/feature/fortuneDetail/FortuneDetailRoute.kt
  feature/fortune/src/main/java/org/sopt/official/feature/fortune/feature/fortuneDetail/FortuneDetailScreen.kt
  feature/fortune/src/main/java/org/sopt/official/feature/fortune/feature/fortuneDetail/FortuneDetailViewModel.kt
  feature/fortune/src/main/java/org/sopt/official/feature/fortune/feature/fortuneDetail/component/FortuneDetailBox.kt
  feature/fortune/src/main/java/org/sopt/official/feature/fortune/feature/fortuneDetail/component/FortuneDetailErrorDialog.kt
  feature/fortune/src/main/java/org/sopt/official/feature/fortune/feature/fortuneDetail/component/PokeMessageBottomSheet.kt
  feature/fortune/src/main/java/org/sopt/official/feature/fortune/feature/fortuneDetail/component/PokeMessageItem.kt
  feature/fortune/src/main/java/org/sopt/official/feature/fortune/feature/fortuneDetail/component/PokeRecommendationDashboard.kt
  feature/fortune/src/main/java/org/sopt/official/feature/fortune/feature/fortuneDetail/component/PokeRecommendationUserProfileImage.kt
  feature/fortune/src/main/java/org/sopt/official/feature/fortune/feature/fortuneDetail/component/PokeSnackBar.kt
  feature/fortune/src/main/java/org/sopt/official/feature/fortune/feature/fortuneDetail/component/TodayFortuneDashboard.kt
  feature/fortune/src/main/java/org/sopt/official/feature/fortune/feature/fortuneDetail/component/TodayFortuneText.kt
  feature/fortune/src/main/java/org/sopt/official/feature/fortune/feature/home/HomeScreen.kt
  feature/fortune/src/main/java/org/sopt/official/feature/fortune/feature/home/navigation/HomeNavGraph.kt
  feature/fortune/src/main/res/drawable/ic_checkbox_off.xml
  feature/fortune/src/main/res/drawable/ic_checkbox_on.xml
Labels: enhancement, size/XXL

#907 [Fix/#871] 마이페이지 오류 수정
  app/src/main/AndroidManifest.xml
  app/src/release/generated/baselineProfiles/baseline-prof.txt
  app/src/release/generated/baselineProfiles/startup-prof.txt
  core/authimpl/src/main/java/org/sopt/official/auth/impl/api/AuthService.kt
  core/authimpl/src/main/java/org/sopt/official/auth/impl/remote/DefaultRemoteAuthDataSource.kt
  core/authimpl/src/main/java/org/sopt/official/auth/impl/repository/AuthRepositoryImpl.kt
  core/authimpl/src/main/java/org/sopt/official/auth/impl/source/RemoteAuthDataSource.kt
  core/network/src/main/java/org/sopt/official/network/authenticator/SoptAuthenticator.kt
  feature/fortune/src/main/java/org/sopt/official/feature/fortune/feature/fortuneDetail/component/FortuneDetailErrorDialog.kt
  feature/mypage/src/main/java/org/sopt/official/feature/mypage/model/MyPageUiModel.kt
  feature/mypage/src/main/java/org/sopt/official/feature/mypage/model/MyPageUiState.kt
  feature/mypage/src/main/java/org/sopt/official/feature/mypage/mypage/MyPageActivity.kt
  feature/mypage/src/main/java/org/sopt/official/feature/mypage/mypage/MyPageViewModel.kt
  feature/mypage/src/main/java/org/sopt/official/feature/mypage/soptamp/nickName/ChangeNickNameActivity.kt
  feature/mypage/src/main/java/org/sopt/official/feature/mypage/soptamp/nickName/ChangeNickNameViewModel.kt
  feature/mypage/src/main/java/org/sopt/official/feature/mypage/soptamp/sentence/AdjustSentenceActivity.kt
  feature/mypage/src/main/java/org/sopt/official/feature/mypage/soptamp/sentence/AdjustSentenceSideEffect.kt
  feature/mypage/src/main/java/org/sopt/official/feature/mypage/soptamp/sentence/AdjustSentenceViewModel.kt
  feature/mypage/src/main/res/layout/activity_change_nick_name.xml
Labels: size/XXL

#920 [feat/#919] SharedPreferences Debugger 추가
  core/network/src/debug/java/org/sopt/official/network/FlipperInitializer.kt
Labels: size/XS

#924 [Feature/#918] fortune 추가 구현
  app/src/release/generated/baselineProfiles/baseline-prof.txt
  app/src/release/generated/baselineProfiles/startup-prof.txt
  core/common/src/main/java/org/sopt/official/common/navigator/DeepLinkType.kt
  feature/fortune/src/main/java/org/sopt/official/feature/fortune/FortuneActivity.kt
  feature/fortune/src/main/java/org/sopt/official/feature/fortune/feature/home/HomeScreen.kt
  feature/notification/src/main/java/org/sopt/official/feature/notification/detail/NotificationDetailActivity.kt
  feature/notification/src/main/java/org/sopt/official/feature/notification/detail/component/ErrorSnackBar.kt
  feature/notification/src/main/res/drawable/ic_error.xml
Labels: size/XXL

#929 [Refactor/#922] 오늘의 솝마디 콕찌르기 BaselineProfile & Spotless 적용
  app/src/release/generated/baselineProfiles/baseline-prof.txt
  app/src/release/generated/baselineProfiles/startup-prof.txt
  feature/fortune/src/main/res/drawable/ic_poke_check.xml
  feature/fortune/src/main/res/drawable/img_fortune_title_small.xml
  feature/notification/src/main/res/drawable/ic_error.xml
Labels: size/XXL

#930 chore: README update
  README.md
Labels: documentation, size/XS

#938 Change baselineProfile.yml
  .github/workflows/baseline-profile.yml
Labels: size/L

#942 [Fix/#904] 웹뷰 이슈 대응
  app/src/main/java/org/sopt/official/feature/home/HomeActivity.kt
  app/src/release/generated/baselineProfiles/baseline-prof.txt
  app/src/release/generated/baselineProfiles/startup-prof.txt
  feature/fortune/src/main/res/drawable/img_fortune_title_large.xml
Labels: size/M
