Repository sopt-makers/sopt-android, pull requests merged in 2024-05, with the labels that each got.

#699 Bump Kotlin, Compose Compiler versions
  README.md
  gradle/libs.versions.toml
Labels: size/S

#700 [feature/reference module] feature/soptamp에서 data/soptamp 직접 참조 수정
  app/src/main/java/org/sopt/official/feature/notification/NotificationDetailActivity.kt
  data/soptamp/src/main/java/org/sopt/official/data/soptamp/di/DataModule.kt
  data/soptamp/src/main/java/org/sopt/official/data/soptamp/remote/model/response/S3URLResponse.kt
  data/soptamp/src/main/java/org/sopt/official/data/soptamp/repository/ImageUploaderRepositoryImpl.kt
  data/soptamp/src/main/java/org/sopt/official/data/soptamp/repository/StampRepositoryImpl.kt
  domain/soptamp/src/main/kotlin/org/sopt/official/domain/soptamp/fake/FakeImageUploaderRepository.kt
  domain/soptamp/src/main/kotlin/org/sopt/official/domain/soptamp/fake/FakeStampRepository.kt
  domain/soptamp/src/main/kotlin/org/sopt/official/domain/soptamp/model/ImageUploadUrl.kt
  domain/soptamp/src/main/kotlin/org/sopt/official/domain/soptamp/repository/ImageUploaderRepository.kt
  domain/soptamp/src/main/kotlin/org/sopt/official/domain/soptamp/repository/StampRepository.kt
  feature/soptamp/build.gradle.kts
  feature/soptamp/src/main/java/org/sopt/official/stamp/feature/mission/detail/MissionDetail.kt
  feature/soptamp/src/main/java/org/sopt/official/stamp/feature/mission/detail/MissionDetailViewModel.kt
Labels: size/L

#710 feat: add new typography
  core/designsystem/src/main/java/org/sopt/official/designsystem/Theme.kt
  core/designsystem/src/main/java/org/sopt/official/designsystem/Type.kt
Labels: enhancement, size/L

#711 [feature/apply-pr-target-in-action] Add pull_request_target trigger in PR Builder action
  .github/workflows/develop_PR_builder.yml
Labels: size/XS

#453 Baseline Profiles 탑재 작업
  .github/workflows/baseline-profile.yml
  app/build.gradle.kts
  app/src/release/generated/baselineProfiles/baseline-prof.txt
  app/src/release/generated/baselineProfiles/startup-prof.txt
  baselineprofile/.gitignore
  baselineprofile/build.gradle.kts
  baselineprofile/src/main/AndroidManifest.xml
  baselineprofile/src/main/java/org/sopt/official/baselineprofile/BaselineProfileGenerator.kt
  baselineprofile/src/main/java/org/sopt/official/baselineprofile/StartupBenchmarks.kt
  build.gradle.kts
  gradle/libs.versions.toml
  settings.gradle.kts
Labels: size/XXL

#713 #709 Feat: Soptamp Darkmode
  .gitignore
  baselineprofile/build.gradle.kts
  baselineprofile/src/main/AndroidManifest.xml
  baselineprofile/src/main/java/org/sopt/official/baselineprofile/BaselineProfileGenerator.kt
  baselineprofile/src/main/java/org/sopt/official/baselineprofile/StartupBenchmarks.kt
  core/designsystem/src/main/java/org/sopt/official/designsystem/Type.kt
  feature/soptamp/src/main/java/org/sopt/official/stamp/designsystem/style/Theme.kt
  gradle/wrapper/gradle-wrapper.properties
Labels: size/L
