Repository sopt-makers/sopt-android, pull requests merged in 2024-11, with the labels that each got.

#957 Bump targetSdk to 35, minSdk to 30
  baselineprofile/build.gradle.kts
  feature/soptamp/src/main/java/org/sopt/official/stamp/feature/mission/list/MissionListScreen.kt
  gradle/libs.versions.toml
Labels: size/S

#979 [Feature/#976] soptlog module
  build-logic/convention/src/main/kotlin/org/sopt/official/plugin/AndroidComposePlugin.kt
  core/designsystem/src/main/java/org/sopt/official/designsystem/component/UrlImage.kt
  feature/fortune/src/main/java/org/sopt/official/feature/fortune/feature/fortuneAmulet/FortuneAmuletScreen.kt
  feature/fortune/src/main/java/org/sopt/official/feature/fortune/feature/fortuneDetail/component/PokeRecommendationUserProfileImage.kt
  feature/soptlog/.gitignore
  feature/soptlog/build.gradle.kts
  feature/soptlog/consumer-rules.pro
  feature/soptlog/src/androidTest/java/org/sopt/official/feature/soptlog/ExampleInstrumentedTest.kt
  feature/soptlog/src/main/AndroidManifest.xml
  feature/soptlog/src/main/java/org/sopt/official/feature/soptlog/SoptlogScreen.kt
  feature/soptlog/src/main/java/org/sopt/official/feature/soptlog/component/SoptlogIntroduction.kt
  feature/soptlog/src/main/java/org/sopt/official/feature/soptlog/component/SoptlogProfile.kt
  feature/soptlog/src/test/java/org/sopt/official/feature/soptlog/ExampleUnitTest.kt
  gradle/libs.versions.toml
  settings.gradle.kts
Labels: size/L

#986 Downgrade kotlin version
  gradle/libs.versions.toml
Labels: size/XS
