Repository sopt-makers/sopt-android, pull requests merged in 2024-01, with the labels that each got.

#529 Renovate year from license header
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/sopt/official/feature/notification/enums/DeepLinkType.kt
  data/mypage/build.gradle.kts
  data/mypage/src/main/java/org/sopt/official/data/mypage/repository/UserRepositoryImpl.kt
  data/poke/build.gradle.kts
  data/poke/src/main/AndroidManifest.xml
  data/poke/src/main/java/org/sopt/official/data/poke/data_source/PokeLocalDataSource.kt
  data/poke/src/main/java/org/sopt/official/data/poke/data_source/PokeRemoteDataSource.kt
  data/poke/src/main/java/org/sopt/official/data/poke/di/ConstantModule.kt
  data/poke/src/main/java/org/sopt/official/data/poke/di/DataStoreModule.kt
  data/poke/src/main/java/org/sopt/official/data/poke/di/PokeQualifier.kt
  data/poke/src/main/java/org/sopt/official/data/poke/dto/request/GetPokeNotificationListRequest.kt
  data/poke/src/main/java/org/sopt/official/data/poke/dto/request/PokeUserRequest.kt
  data/poke/src/main/java/org/sopt/official/data/poke/dto/response/GetFriendListDetailResult.kt
  data/poke/src/main/java/org/sopt/official/data/poke/dto/response/PokeNotificationResult.kt
  data/poke/src/main/java/org/sopt/official/data/poke/repository_impl/PokeRepositoryImpl.kt
  data/poke/src/main/java/org/sopt/official/data/poke/service/PokeService.kt
  domain/poke/src/main/java/org/sopt/official/domain/poke/entity/GetFriendListDetailResponse.kt
  domain/poke/src/main/java/org/sopt/official/domain/poke/entity/GetPokeNotificationListResponse.kt
  domain/poke/src/main/java/org/sopt/official/domain/poke/repository/PokeRepository.kt
  domain/poke/src/main/java/org/sopt/official/domain/poke/use_case/CheckNewInPokeOnboardingUseCase.kt
  domain/poke/src/main/java/org/sopt/official/domain/poke/use_case/CheckNewInPokeUseCase.kt
  domain/poke/src/main/java/org/sopt/official/domain/poke/use_case/GetFriendListDetailUseCase.kt
  domain/poke/src/main/java/org/sopt/official/domain/poke/use_case/GetFriendListSummaryUseCase.kt
  domain/poke/src/main/java/org/sopt/official/domain/poke/use_case/GetOnboardingPokeUserListUseCase.kt
  domain/poke/src/main/java/org/sopt/official/domain/poke/use_case/PokeUserUseCase.kt
  domain/poke/src/main/java/org/sopt/official/domain/poke/use_case/UpdateNewInPokeOnboardingUseCase.kt
  feature/poke/src/main/AndroidManifest.xml
  feature/poke/src/main/java/org/sopt/official/feature/poke/UiState.kt
  feature/poke/src/main/java/org/sopt/official/feature/poke/friend_list_detail/FriendListDetailBottomSheetFragment.kt
  feature/poke/src/main/java/org/sopt/official/feature/poke/friend_list_detail/FriendListDetailViewModel.kt
  feature/poke/src/main/java/org/sopt/official/feature/poke/friend_list_summary/FriendListSummaryActivity.kt
  feature/poke/src/main/java/org/sopt/official/feature/poke/friend_list_summary/FriendListSummaryViewModel.kt
  feature/poke/src/main/java/org/sopt/official/feature/poke/main/PokeMainActivity.kt
  feature/poke/src/main/java/org/sopt/official/feature/poke/main/PokeMainViewModel.kt
  feature/poke/src/main/java/org/sopt/official/feature/poke/message_bottom_sheet/MessageListBottomSheetViewModel.kt
  feature/poke/src/main/java/org/sopt/official/feature/poke/message_bottom_sheet/MessageListRecyclerAdapter.kt
  feature/poke/src/main/java/org/sopt/official/feature/poke/notification/PokeNotificationActivity.kt
  feature/poke/src/main/java/org/sopt/official/feature/poke/notification/PokeNotificationAdapter.kt
  feature/poke/src/main/java/org/sopt/official/feature/poke/notification/PokeNotificationViewModel.kt
  feature/poke/src/main/java/org/sopt/official/feature/poke/onboarding/OnboardingActivity.kt
  feature/poke/src/main/java/org/sopt/official/feature/poke/onboarding/OnboardingBottomSheetFragment.kt
  feature/poke/src/main/java/org/sopt/official/feature/poke/onboarding/OnboardingViewModel.kt
  feature/poke/src/main/java/org/sopt/official/feature/poke/poke_user_recycler_view/PokeUserViewHolder.kt
  feature/poke/src/main/java/org/sopt/official/feature/poke/util/PokeUtil.kt
  feature/poke/src/main/res/drawable/ic_empty_poke.xml
  feature/poke/src/main/res/drawable/icon_success.xml
  feature/poke/src/main/res/layout/activity_poke_main.xml
  feature/poke/src/main/res/layout/activity_poke_notification.xml
  feature/poke/src/main/res/layout/item_poke_notification_header.xml
  feature/poke/src/main/res/layout/toast_poke.xml
  feature/poke/src/main/res/values/strings.xml
Labels: size/L

#537 Bump Kotlin Versions
  README.md
  gradle/libs.versions.toml
Labels: size/XS

#548 Add pokeDataStoreKey in merge builder
  .github/workflows/develop_merge_builder.yml
Labels: size/XS

#552 [Fix/#551] 비회원일 경우 솜템프 버튼 클릭 시 진입 불가 다이얼로그 뜨도록 코드 추가
  app/src/main/java/org/sopt/official/feature/home/HomeActivity.kt
  app/src/main/res/values/strings.xml
Labels: size/S
