Repository sopt-makers/sopt-android, pull requests merged in 2025-02, with the labels that each got.

#1046 [FEATURE/#1033] Schedule Feature UI
  feature/schedule/.gitignore
  feature/schedule/build.gradle.kts
  feature/schedule/consumer-rules.pro
  feature/schedule/src/main/AndroidManifest.xml
  feature/schedule/src/main/java/com/sopt/official/feature/schedule/ScheduleActivity.kt
  feature/schedule/src/main/java/com/sopt/official/feature/schedule/component/ScheduleItem.kt
  feature/schedule/src/main/java/com/sopt/official/feature/schedule/component/VerticalDividerWithCircle.kt
  settings.gradle.kts
Labels: size/L

#1048 [Feature/#1047] SoptLog에 api를 연결합니다.
  app/build.gradle.kts
  core/designsystem/src/main/java/org/sopt/official/designsystem/component/UrlImage.kt
  core/designsystem/src/main/res/drawable/img_fake_red.xml
  data/soptlog/.gitignore
  data/soptlog/build.gradle.kts
  data/soptlog/consumer-rules.pro
  data/soptlog/src/main/AndroidManifest.xml
  data/soptlog/src/main/java/org/sopt/official/data/soptlog/api/SoptLogApi.kt
  data/soptlog/src/main/java/org/sopt/official/data/soptlog/di/ApiModule.kt
  data/soptlog/src/main/java/org/sopt/official/data/soptlog/di/RepositoryModule.kt
  data/soptlog/src/main/java/org/sopt/official/data/soptlog/dto/SoptLogInfoResponse.kt
  data/soptlog/src/main/java/org/sopt/official/data/soptlog/mapper/SoptLogMapper.kt
  data/soptlog/src/main/java/org/sopt/official/data/soptlog/repository/DefaultSoptLogRepository.kt
  domain/soptlog/.gitignore
  domain/soptlog/build.gradle.kts
  domain/soptlog/src/main/java/org/sopt/official/domain/soptlog/model/SoptLogInfo.kt
  domain/soptlog/src/main/java/org/sopt/official/domain/soptlog/repository/SoptLogRepository.kt
  feature/soptlog/build.gradle.kts
  feature/soptlog/src/androidTest/java/org/sopt/official/feature/soptlog/ExampleInstrumentedTest.kt
  feature/soptlog/src/main/java/org/sopt/official/feature/soptlog/SoptLogViewModel.kt
  feature/soptlog/src/main/java/org/sopt/official/feature/soptlog/SoptlogScreen.kt
  feature/soptlog/src/main/java/org/sopt/official/feature/soptlog/component/SoptlogDashboard.kt
  feature/soptlog/src/main/java/org/sopt/official/feature/soptlog/component/SoptlogIntroduction.kt
  feature/soptlog/src/main/java/org/sopt/official/feature/soptlog/component/SoptlogProfile.kt
  feature/soptlog/src/main/res/drawable/ic_calender.xml
  feature/soptlog/src/main/res/drawable/ic_empty_profile.xml
  feature/soptlog/src/main/res/drawable/ic_poke_hand.xml
  feature/soptlog/src/main/res/drawable/ic_sopt_level.xml
  feature/soptlog/src/main/res/drawable/ic_soptamp_hand.xml
  feature/soptlog/src/test/java/org/sopt/official/feature/soptlog/ExampleUnitTest.kt
  gradle/libs.versions.toml
  settings.gradle.kts
Labels: size/XL

#1050 [Feature/#1049] Schedule 화면에 api를 연결합니다.
  app/build.gradle.kts
  data/schedule/.gitignore
  data/schedule/build.gradle.kts
  data/schedule/consumer-rules.pro
  data/schedule/src/main/AndroidManifest.xml
  data/schedule/src/main/java/org/sopt/official/data/schedule/api/ScheduleApi.kt
  data/schedule/src/main/java/org/sopt/official/data/schedule/di/ApiModule.kt
  data/schedule/src/main/java/org/sopt/official/data/schedule/di/RepositoryModule.kt
  data/schedule/src/main/java/org/sopt/official/data/schedule/dto/ScheduleResponse.kt
  data/schedule/src/main/java/org/sopt/official/data/schedule/mapper/ScheduleMapper.kt
  data/schedule/src/main/java/org/sopt/official/data/schedule/repository/DefaultScheduleRepository.kt
  domain/schedule/.gitignore
  domain/schedule/build.gradle.kts
  domain/schedule/src/main/java/org/sopt/official/domain/schedule/model/Schedule.kt
  domain/schedule/src/main/java/org/sopt/official/domain/schedule/repository/ScheduleRepository.kt
  feature/schedule/build.gradle.kts
  feature/schedule/src/main/java/org/sopt/official/feature/schedule/ScheduleActivity.kt
  feature/schedule/src/main/java/org/sopt/official/feature/schedule/ScheduleViewModel.kt
  feature/schedule/src/main/java/org/sopt/official/feature/schedule/component/ScheduleItem.kt
  feature/schedule/src/main/java/org/sopt/official/feature/schedule/component/VerticalDividerWithCircle.kt
  settings.gradle.kts
Labels: size/L

#1060 [Feature/#1059] app Main을 구현하고 네비를 연결합니다.
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/sopt/official/feature/auth/AuthActivity.kt
  build-logic/convention/src/main/kotlin/org/sopt/official/plugin/AndroidComposePlugin.kt
  core/navigation/.gitignore
  core/navigation/build.gradle.kts
  core/navigation/src/main/java/org/sopt/official/core/navigation/Route.kt
  feature/main/.gitignore
  feature/main/build.gradle.kts
  feature/main/consumer-rules.pro
  feature/main/src/main/AndroidManifest.xml
  feature/main/src/main/java/org/sopt/official/feature/main/DummyScreen.kt
  feature/main/src/main/java/org/sopt/official/feature/main/MainActivity.kt
  feature/main/src/main/java/org/sopt/official/feature/main/MainNavigator.kt
  feature/main/src/main/java/org/sopt/official/feature/main/MainScreen.kt
  feature/main/src/main/java/org/sopt/official/feature/main/MainTab.kt
  feature/soptlog/build.gradle.kts
  feature/soptlog/src/main/java/org/sopt/official/feature/soptlog/SoptlogScreen.kt
  feature/soptlog/src/main/java/org/sopt/official/feature/soptlog/component/SoptlogIntroduction.kt
  feature/soptlog/src/main/java/org/sopt/official/feature/soptlog/navigation/SoptlogNavigation.kt
  settings.gradle.kts
Labels: size/XL

#1072 [Feature/#1063] 홈 화면 개편(3) - 홈 화면 QA 사항 반영
  app/src/main/java/org/sopt/official/feature/navigator/NavigatorProviderIntent.kt
  build-logic/convention/src/main/kotlin/org/sopt/official/plugin/CommonConfigs.kt
  core/common/src/main/java/org/sopt/official/common/navigator/NavigatorProvider.kt
  feature/fortune/src/androidTest/java/org/sopt/official/feature/fortune/fortuneDetail/FortuneDetailScreenTest.kt
  feature/home/build.gradle.kts
  feature/home/src/androidTest/java/org/sopt/official/ExampleInstrumentedTest.kt
  feature/home/src/main/java/org/sopt/official/feature/home/HomeRoute.kt
  feature/home/src/main/java/org/sopt/official/feature/home/NewHomeViewModel.kt
  feature/home/src/main/java/org/sopt/official/feature/home/component/HomeEnjoySoptServicesBlock.kt
  feature/home/src/main/java/org/sopt/official/feature/home/component/HomeGenerationChips.kt
  feature/home/src/main/java/org/sopt/official/feature/home/component/HomeUserSoptLogDashboard.kt
  feature/home/src/main/java/org/sopt/official/feature/home/model/HomeUiState.kt
  feature/home/src/main/java/org/sopt/official/feature/home/model/Schedule.kt
  feature/home/src/main/java/org/sopt/official/feature/home/navigation/HomeNavigation.kt
  feature/home/src/main/java/org/sopt/official/feature/home/navigation/HomeNavigator.kt
  feature/home/src/main/res/drawable/ic_arrow_right.xml
  feature/home/src/main/res/drawable/ic_check_filled.xml
  feature/home/src/main/res/drawable/ic_folder.xml
  feature/home/src/main/res/drawable/ic_homepage.xml
  feature/home/src/main/res/drawable/ic_instagram.xml
  feature/home/src/main/res/drawable/ic_member.xml
  feature/home/src/main/res/drawable/ic_notification_off.xml
  feature/home/src/main/res/drawable/ic_notification_on.xml
  feature/home/src/main/res/drawable/ic_pencil.xml
  feature/home/src/main/res/drawable/ic_project.xml
  feature/home/src/main/res/drawable/ic_setting.xml
  feature/home/src/main/res/drawable/ic_soptlog.xml
  feature/home/src/main/res/drawable/img_poke.png
  feature/home/src/main/res/drawable/img_soptamp.png
  feature/home/src/main/res/drawable/img_soptmadi.png
  feature/home/src/main/res/drawable/is_playground.xml
  feature/home/src/test/java/org/sopt/official/ExampleUnitTest.kt
  feature/main/build.gradle.kts
  feature/main/src/main/java/org/sopt/official/feature/main/MainNavigator.kt
  feature/main/src/main/java/org/sopt/official/feature/main/MainScreen.kt
  feature/main/src/main/java/org/sopt/official/feature/main/model/WebLink.kt
Labels: size/L

#1034 Revert "[Feature/#928] 로그인 중앙화 UI 구현 (#1008)"
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/sopt/official/feature/auth/AuthActivity.kt
  app/src/main/java/org/sopt/official/feature/auth/AuthViewModel.kt
  app/src/main/java/org/sopt/official/feature/auth/component/AuthButton.kt
  app/src/main/java/org/sopt/official/feature/auth/component/AuthTextField.kt
  app/src/main/java/org/sopt/official/feature/auth/component/AuthTextWithArrow.kt
  app/src/main/java/org/sopt/official/feature/auth/component/CertificationSnackBar.kt
  app/src/main/java/org/sopt/official/feature/auth/component/LoginErrorDialog.kt
  app/src/main/java/org/sopt/official/feature/auth/component/PhoneCertification.kt
  app/src/main/java/org/sopt/official/feature/auth/feature/autherror/AuthErrorScreen.kt
  app/src/main/java/org/sopt/official/feature/auth/feature/certificatemember/CertificateMemberScreen.kt
  app/src/main/java/org/sopt/official/feature/auth/feature/socialaccount/CertificateAccountScreen.kt
  app/src/main/java/org/sopt/official/feature/auth/feature/socialaccount/ChangeAccountScreen.kt
  app/src/main/res/drawable/ic_auth_alert_circle.xml
  app/src/main/res/drawable/ic_auth_arrow_right.xml
  app/src/main/res/drawable/ic_auth_certification_error.xml
  app/src/main/res/drawable/ic_auth_certification_notice.xml
  app/src/main/res/drawable/ic_auth_error.xml
  app/src/main/res/drawable/ic_auth_google.xml
  app/src/main/res/drawable/ic_auth_memeber_error.xml
  app/src/main/res/drawable/ic_auth_process.xml
  app/src/main/res/layout/activity_auth.xml
  app/src/main/res/xml/backup_rules.xml
  app/src/release/generated/baselineProfiles/baseline-prof.txt
  app/src/release/generated/baselineProfiles/startup-prof.txt
  core/common/src/main/java/org/sopt/official/common/util/SecurityExt.kt
  core/designsystem/src/main/java/org/sopt/official/designsystem/Color.kt
  core/security/src/androidTest/java/org/sopt/official/security/CryptoManagerTest.kt
Labels: size/XXL

#947 [feature/#946] WebView에 사진 다운로드 기능 추가
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/sopt/official/App.kt
  app/src/release/generated/baselineProfiles/baseline-prof.txt
  app/src/release/generated/baselineProfiles/startup-prof.txt
  core/webview/build.gradle.kts
  core/webview/src/main/java/org/sopt/official/webview/view/WebViewActivity.kt
  gradle/libs.versions.toml
  settings.gradle.kts
Labels: size/L

#1076 [FIX] Null 설정 관련 수정
  core/webview/src/main/java/org/sopt/official/webview/view/WebViewActivity.kt
Labels: size/XS

#1081 [feature/home-navigation] HomeActivity -> MainActivity
  app/src/main/java/org/sopt/official/feature/auth/AuthActivity.kt
Labels: size/XS

#1082 Update github action yml
  .github/workflows/develop_PR_builder.yml
  .github/workflows/develop_merge_builder.yml
Labels: size/XS

#1083 HomeActivity -> MainActivity
  app/src/main/java/org/sopt/official/feature/auth/AuthActivity.kt
Labels: size/XS
