Repository sopt-makers/sopt-android, pull requests merged in 2025-04, with the labels that each got.

#1145 [login-core] 소셜 로그인 기능 구현: core 모듈 쪽 원복
  build-logic/convention/src/main/kotlin/org/sopt/official/plugin/CommonConfigs.kt
  core/auth/src/main/kotlin/org/sopt/official/auth/model/CentralizeToken.kt
  core/auth/src/main/kotlin/org/sopt/official/auth/repository/AuthRepository.kt
  core/auth/src/main/kotlin/org/sopt/official/auth/repository/CentralizeAuthRepository.kt
  core/authimpl/src/main/java/org/sopt/official/auth/impl/mapper/AuthMapper.kt
  core/authimpl/src/main/java/org/sopt/official/auth/impl/mapper/TokenMapper.kt
  core/authimpl/src/main/java/org/sopt/official/auth/impl/repository/AuthRepositoryImpl.kt
  core/authimpl/src/main/java/org/sopt/official/auth/impl/repository/DefaultCentralizeAuthRepository.kt
  core/common/src/main/java/org/sopt/official/common/di/Qualifiers.kt
  core/network/src/main/java/org/sopt/official/network/authenticator/CentralizeAuthenticator.kt
  core/network/src/main/java/org/sopt/official/network/authenticator/SoptAuthenticator.kt
  core/network/src/main/java/org/sopt/official/network/di/AuthModule.kt
  core/network/src/main/java/org/sopt/official/network/di/NetModule.kt
  core/network/src/main/java/org/sopt/official/network/model/request/ExpiredTokenRequest.kt
  core/network/src/main/java/org/sopt/official/network/model/request/RefreshRequest.kt
  core/network/src/main/java/org/sopt/official/network/model/response/AuthResponse.kt
  core/network/src/main/java/org/sopt/official/network/model/response/RefreshTokenResponse.kt
  core/network/src/main/java/org/sopt/official/network/persistence/SoptDataStore.kt
  core/network/src/main/java/org/sopt/official/network/service/RefreshApi.kt
  core/network/src/main/java/org/sopt/official/network/service/RefreshService.kt
Labels: size/L

#1146 [delete-home] app 모듈 내에 기존 홈 코드를 삭제합니다.
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/sopt/official/data/model/home/AppServiceResponse.kt
  app/src/main/java/org/sopt/official/data/model/home/DescriptionViewResponse.kt
  app/src/main/java/org/sopt/official/data/model/home/HomeResponse.kt
  app/src/main/java/org/sopt/official/data/model/home/HotPostResponse.kt
  app/src/main/java/org/sopt/official/data/repository/home/DefaultHomeRepository.kt
  app/src/main/java/org/sopt/official/data/service/home/HomeService.kt
  app/src/main/java/org/sopt/official/di/HomeModule.kt
  app/src/main/java/org/sopt/official/domain/entity/home/AppService.kt
  app/src/main/java/org/sopt/official/domain/entity/home/Home.kt
  app/src/main/java/org/sopt/official/domain/entity/home/HotPostEntity.kt
  app/src/main/java/org/sopt/official/domain/repository/home/HomeRepository.kt
  app/src/main/java/org/sopt/official/feature/home/HomeActivity.kt
  app/src/main/java/org/sopt/official/feature/home/HomeViewModel.kt
  app/src/main/java/org/sopt/official/feature/home/adapter/SmallBlockAdapter.kt
  app/src/main/java/org/sopt/official/feature/home/model/AppServiceUiState.kt
  app/src/main/java/org/sopt/official/feature/home/model/HomeCTAType.kt
  app/src/main/java/org/sopt/official/feature/home/model/HomeMenuType.kt
  app/src/main/java/org/sopt/official/feature/home/model/SoptMainContentUrl.kt
  app/src/main/java/org/sopt/official/feature/home/model/UserActiveGeneration.kt
  app/src/main/java/org/sopt/official/feature/home/model/UserUiState.kt
  app/src/main/res/layout/activity_sopt_main.xml
  app/src/release/generated/baselineProfiles/baseline-prof.txt
  app/src/release/generated/baselineProfiles/startup-prof.txt
  feature/home/build.gradle.kts
  gradle/libs.versions.toml
Labels: size/XXL

#1148 [FEAT/#1147] 솝탬프 mds 적용
  app/src/main/AndroidManifest.xml
  core/common/src/main/java/org/sopt/official/common/util/ContentUriRequestBody.kt
  core/designsystem/src/main/res/values/themes.xml
  data/soptamp/src/main/java/org/sopt/official/data/soptamp/repository/ImageUploaderRepositoryImpl.kt
  feature/soptamp/build.gradle.kts
  feature/soptamp/src/main/java/org/sopt/official/stamp/SoptampActivity.kt
  feature/soptamp/src/main/java/org/sopt/official/stamp/designsystem/component/button/SoptampButton.kt
  feature/soptamp/src/main/java/org/sopt/official/stamp/designsystem/component/button/SoptampFloatingButton.kt
  feature/soptamp/src/main/java/org/sopt/official/stamp/designsystem/component/button/SoptampIconButton.kt
  feature/soptamp/src/main/java/org/sopt/official/stamp/designsystem/component/button/SoptampSegmentedFloatingButton.kt
  feature/soptamp/src/main/java/org/sopt/official/stamp/designsystem/component/dialog/DoubleOptionDialog.kt
  feature/soptamp/src/main/java/org/sopt/official/stamp/designsystem/component/dialog/ErrorDialog.kt
  feature/soptamp/src/main/java/org/sopt/official/stamp/designsystem/component/dialog/SingleOptionDialog.kt
  feature/soptamp/src/main/java/org/sopt/official/stamp/designsystem/component/layout/Layout.kt
  feature/soptamp/src/main/java/org/sopt/official/stamp/designsystem/component/layout/LoadingScreen.kt
  feature/soptamp/src/main/java/org/sopt/official/stamp/designsystem/component/mission/MissionComponent.kt
  feature/soptamp/src/main/java/org/sopt/official/stamp/designsystem/component/mission/MissionShape.kt
  feature/soptamp/src/main/java/org/sopt/official/stamp/designsystem/component/mission/Stamp.kt
  feature/soptamp/src/main/java/org/sopt/official/stamp/designsystem/component/ratingbar/RatingBar.kt
  feature/soptamp/src/main/java/org/sopt/official/stamp/designsystem/component/toolbar/Toolbar.kt
  feature/soptamp/src/main/java/org/sopt/official/stamp/designsystem/component/topappbar/SoptTopAppBar.kt
  feature/soptamp/src/main/java/org/sopt/official/stamp/designsystem/style/Color.kt
  feature/soptamp/src/main/java/org/sopt/official/stamp/designsystem/style/Theme.kt
  feature/soptamp/src/main/java/org/sopt/official/stamp/feature/mission/MissionsViewModel.kt
  feature/soptamp/src/main/java/org/sopt/official/stamp/feature/mission/detail/MissionDetail.kt
  feature/soptamp/src/main/java/org/sopt/official/stamp/feature/mission/detail/MissionDetailViewModel.kt
  feature/soptamp/src/main/java/org/sopt/official/stamp/feature/mission/detail/component/DatePicker.kt
  feature/soptamp/src/main/java/org/sopt/official/stamp/feature/mission/detail/component/Header.kt
  feature/soptamp/src/main/java/org/sopt/official/stamp/feature/mission/detail/component/ImageContent.kt
  feature/soptamp/src/main/java/org/sopt/official/stamp/feature/mission/detail/component/Memo.kt
  feature/soptamp/src/main/java/org/sopt/official/stamp/feature/mission/list/MissionListScreen.kt
  feature/soptamp/src/main/java/org/sopt/official/stamp/feature/mission/list/UserMissionListScreen.kt
  feature/soptamp/src/main/java/org/sopt/official/stamp/feature/onboarding/OnboardingPage.kt
  feature/soptamp/src/main/java/org/sopt/official/stamp/feature/onboarding/OnboardingScreen.kt
  feature/soptamp/src/main/java/org/sopt/official/stamp/feature/ranking/RankColor.kt
  feature/soptamp/src/main/java/org/sopt/official/stamp/feature/ranking/RankListItem.kt
  feature/soptamp/src/main/java/org/sopt/official/stamp/feature/ranking/RankNumber.kt
  feature/soptamp/src/main/java/org/sopt/official/stamp/feature/ranking/RankScore.kt
  feature/soptamp/src/main/java/org/sopt/official/stamp/feature/ranking/TopRankerItem.kt
  feature/soptamp/src/main/java/org/sopt/official/stamp/feature/ranking/TopRankerList.kt
  feature/soptamp/src/main/java/org/sopt/official/stamp/feature/ranking/part/PartRankingScreen.kt
  feature/soptamp/src/main/java/org/sopt/official/stamp/feature/ranking/rank/RankingScreen.kt
  feature/soptamp/src/main/res/drawable/ic_close_32.xml
  feature/soptamp/src/main/res/drawable/ic_onboarding_1.xml
  feature/soptamp/src/main/res/drawable/ic_onboarding_2.xml
  feature/soptamp/src/main/res/drawable/ic_onboarding_3.xml
Labels: size/XXL

#1158 [FIX/#1157] 솝탬프 qa 반영
  data/soptamp/src/main/java/org/sopt/official/data/soptamp/remote/model/request/StampRequest.kt
  feature/soptamp/src/main/java/org/sopt/official/stamp/designsystem/component/button/SoptampFloatingButton.kt
  feature/soptamp/src/main/java/org/sopt/official/stamp/designsystem/component/mission/MissionComponent.kt
  feature/soptamp/src/main/java/org/sopt/official/stamp/feature/mission/detail/component/Header.kt
  feature/soptamp/src/main/java/org/sopt/official/stamp/feature/mission/list/MissionListScreen.kt
  feature/soptamp/src/main/java/org/sopt/official/stamp/feature/ranking/RankColor.kt
  feature/soptamp/src/main/res/drawable/empty_mission.xml
  feature/soptamp/src/main/res/drawable/ic_empty_mission.xml
Labels: size/L

#1161 [FIX/#1160] 솝탬프 관련 기능 난독화 문제 해결
  data/mypage/src/main/java/org/sopt/official/data/mypage/model/request/UpdateProfileMessageRequest.kt
  data/mypage/src/main/java/org/sopt/official/data/mypage/model/response/UpdateProfileMessageResponse.kt
  data/soptamp/src/main/java/org/sopt/official/data/soptamp/remote/model/response/ModifyStampResponse.kt
  feature/soptamp/src/main/java/org/sopt/official/stamp/feature/mission/detail/MissionDetailViewModel.kt
Labels: bug, size/S

#1168 [Feat/#1167] 특별 미션 UI구현
  domain/soptamp/src/main/kotlin/org/sopt/official/domain/soptamp/MissionLevel.kt
  feature/soptamp/src/main/java/org/sopt/official/stamp/designsystem/component/mission/LevelOfMission.kt
  feature/soptamp/src/main/java/org/sopt/official/stamp/designsystem/component/mission/SpecialMissonTitle.kt
  feature/soptamp/src/main/java/org/sopt/official/stamp/designsystem/component/mission/Stamp.kt
  feature/soptamp/src/main/java/org/sopt/official/stamp/designsystem/style/Color.kt
  feature/soptamp/src/main/java/org/sopt/official/stamp/feature/mission/detail/MissionDetail.kt
  feature/soptamp/src/main/java/org/sopt/official/stamp/feature/mission/detail/component/Header.kt
  feature/soptamp/src/main/java/org/sopt/official/stamp/feature/mission/list/MissionListScreen.kt
  feature/soptamp/src/main/java/org/sopt/official/stamp/feature/mission/model/MissionListUiModel.kt
  feature/soptamp/src/main/res/drawable/ic_text_close.xml
  feature/soptamp/src/main/res/drawable/orangestamp_iamge.xml
  feature/soptamp/src/main/res/raw/orangestamp.json
Labels: size/XXL

#1171 [FEAT/#1169] 안드로이드 15 대응
  core/webview/src/main/java/org/sopt/official/webview/view/WebViewActivity.kt
  core/webview/src/main/res/layout/activity_web_view.xml
  feature/fortune/src/main/java/org/sopt/official/feature/fortune/FortuneActivity.kt
  feature/fortune/src/main/java/org/sopt/official/feature/fortune/FoundationScreen.kt
  feature/home/src/main/java/org/sopt/official/feature/home/HomeRoute.kt
  feature/home/src/main/java/org/sopt/official/feature/home/navigation/HomeNavigator.kt
  feature/main/src/main/java/org/sopt/official/feature/main/MainActivity.kt
  feature/main/src/main/java/org/sopt/official/feature/main/MainScreen.kt
  feature/poke/src/main/java/org/sopt/official/feature/poke/friend/summary/FriendListSummaryActivity.kt
  feature/poke/src/main/java/org/sopt/official/feature/poke/main/PokeMainActivity.kt
  feature/poke/src/main/java/org/sopt/official/feature/poke/notification/PokeNotificationActivity.kt
  feature/poke/src/main/java/org/sopt/official/feature/poke/onboarding/OnboardingActivity.kt
  feature/poke/src/main/res/layout/activity_friend_list_summary.xml
  feature/poke/src/main/res/layout/activity_onboarding.xml
  feature/poke/src/main/res/layout/activity_poke_main.xml
  feature/poke/src/main/res/layout/activity_poke_notification.xml
  feature/soptamp/src/main/java/org/sopt/official/stamp/SoptampActivity.kt
  feature/soptamp/src/main/java/org/sopt/official/stamp/feature/mission/detail/MissionDetail.kt
  feature/soptamp/src/main/java/org/sopt/official/stamp/feature/mission/list/MissionListScreen.kt
  feature/soptamp/src/main/java/org/sopt/official/stamp/feature/onboarding/OnboardingScreen.kt
  feature/soptamp/src/main/java/org/sopt/official/stamp/feature/ranking/part/PartRankingScreen.kt
  feature/soptamp/src/main/java/org/sopt/official/stamp/feature/ranking/rank/RankingScreen.kt
Labels: size/M

#1177 [FEAT/#1162] 홈 FAB 구현
  core/designsystem/src/main/java/org/sopt/official/designsystem/Type.kt
  feature/main/src/main/java/org/sopt/official/feature/main/MainFloatingButton.kt
  feature/main/src/main/java/org/sopt/official/feature/main/MainScreen.kt
  feature/main/src/main/java/org/sopt/official/feature/main/model/WebLink.kt
  feature/main/src/main/res/drawable/ic_bolt_22.xml
  feature/main/src/main/res/drawable/ic_close_28.xml
  feature/main/src/main/res/drawable/ic_feed_22.xml
  feature/main/src/main/res/drawable/ic_moim_22.xml
  feature/main/src/main/res/drawable/ic_pencil_22.xml
  feature/main/src/main/res/drawable/ic_sopticle_22.xml
Labels: size/L
