Repository sopt-makers/sopt-android, pull requests merged in 2025-07, with the labels that each got.

#1250 Bump Kotlin 2.2.0
  baselineprofile/build.gradle.kts
  gradle/libs.versions.toml
Labels: size/S

#1223 [FEAT/#1178] 로그인 중앙화 Dev 서버 연동
  app/build.gradle.kts
  app/proguard-rules.pro
  app/src/main/java/org/sopt/official/feature/auth/AuthActivity.kt
  app/src/main/java/org/sopt/official/feature/auth/AuthScreen.kt
  app/src/main/java/org/sopt/official/feature/auth/AuthSideEffect.kt
  app/src/main/java/org/sopt/official/feature/auth/AuthViewModel.kt
  app/src/main/java/org/sopt/official/feature/auth/component/LoginErrorDialog.kt
  app/src/main/java/org/sopt/official/feature/auth/feature/autherror/AuthErrorScreen.kt
  app/src/main/java/org/sopt/official/feature/auth/feature/autherror/navigation/AuthErrorNavigation.kt
  app/src/main/java/org/sopt/official/feature/auth/feature/authmain/AuthMainScreen.kt
  app/src/main/java/org/sopt/official/feature/auth/feature/authmain/AuthMainSideEffect.kt
  app/src/main/java/org/sopt/official/feature/auth/feature/authmain/AuthMainViewModel.kt
  app/src/main/java/org/sopt/official/feature/auth/feature/authmain/navigation/AuthMainNavigation.kt
  app/src/main/java/org/sopt/official/feature/auth/feature/certificate/CertificationScreen.kt
  app/src/main/java/org/sopt/official/feature/auth/feature/certificate/CertificationSideEffect.kt
  app/src/main/java/org/sopt/official/feature/auth/feature/certificate/CertificationViewModel.kt
  app/src/main/java/org/sopt/official/feature/auth/feature/certificate/navigation/CertificationNavigation.kt
  app/src/main/java/org/sopt/official/feature/auth/feature/socialaccount/SocialAccountScreen.kt
  app/src/main/java/org/sopt/official/feature/auth/feature/socialaccount/SocialAccountSideEffect.kt
  app/src/main/java/org/sopt/official/feature/auth/feature/socialaccount/SocialAccountState.kt
  app/src/main/java/org/sopt/official/feature/auth/feature/socialaccount/SocialAccountViewModel.kt
  app/src/main/java/org/sopt/official/feature/auth/feature/socialaccount/navigation/SocialAccountNavigation.kt
  app/src/main/java/org/sopt/official/feature/auth/model/AuthStatus.kt
  app/src/main/java/org/sopt/official/feature/auth/utils/GoogleLoginManager.kt
  app/src/main/java/org/sopt/official/feature/auth/utils/di/GoogleLoginEntryPoint.kt
  build-logic/convention/src/main/kotlin/org/sopt/official/plugin/CommonConfigs.kt
  core/common/src/main/java/org/sopt/official/common/coroutines/runCatching.kt
  core/network/src/main/java/org/sopt/official/network/di/NetModule.kt
  data/auth/src/main/java/org/sopt/official/data/auth/mapper/CertificateCodeMapper.kt
  data/auth/src/main/java/org/sopt/official/data/auth/mapper/ChangeAccountMapper.kt
  data/auth/src/main/java/org/sopt/official/data/auth/mapper/CreateCodeMapper.kt
  data/auth/src/main/java/org/sopt/official/data/auth/mapper/FindAccountMapper.kt
  data/auth/src/main/java/org/sopt/official/data/auth/mapper/SignInMapper.kt
  data/auth/src/main/java/org/sopt/official/data/auth/mapper/SignUpMapper.kt
  data/auth/src/main/java/org/sopt/official/data/auth/remote/api/AuthApi.kt
  data/auth/src/main/java/org/sopt/official/data/auth/remote/request/CertificateCodeRequest.kt
  data/auth/src/main/java/org/sopt/official/data/auth/remote/request/SignUpRequest.kt
  data/auth/src/main/java/org/sopt/official/data/auth/repository/DefaultAuthRepository.kt
  domain/auth/src/main/java/org/sopt/official/domain/auth/model/AccountResult.kt
  domain/auth/src/main/java/org/sopt/official/domain/auth/model/Auth.kt
  domain/auth/src/main/java/org/sopt/official/domain/auth/model/InformationWithCode.kt
  domain/auth/src/main/java/org/sopt/official/domain/auth/model/InitialInformation.kt
  domain/auth/src/main/java/org/sopt/official/domain/auth/model/OriginalInformation.kt
  domain/auth/src/main/java/org/sopt/official/domain/auth/model/SignInCode.kt
  domain/auth/src/main/java/org/sopt/official/domain/auth/model/SignUpCode.kt
  domain/auth/src/main/java/org/sopt/official/domain/auth/model/Token.kt
  domain/auth/src/main/java/org/sopt/official/domain/auth/model/User.kt
  domain/auth/src/main/java/org/sopt/official/domain/auth/model/UserPhoneNumber.kt
  domain/auth/src/main/java/org/sopt/official/domain/auth/model/VerificationResult.kt
  domain/auth/src/main/java/org/sopt/official/domain/auth/repository/AuthRepository.kt
  feature/auth/src/main/java/org/sopt/official/auth/PlaygroundAuth.kt
  gradle/libs.versions.toml
Labels: size/XXL

#1272 [FEAT/#1225] 로그인 중앙화 Dev 서버 중간 작업
  app/src/main/java/org/sopt/official/feature/auth/AuthActivity.kt
  app/src/main/java/org/sopt/official/feature/auth/component/LoginErrorDialog.kt
  app/src/main/java/org/sopt/official/feature/auth/feature/authmain/AuthMainScreen.kt
  app/src/main/java/org/sopt/official/feature/auth/feature/authmain/AuthMainViewModel.kt
  app/src/main/java/org/sopt/official/feature/auth/feature/socialaccount/SocialAccountScreen.kt
  app/src/main/java/org/sopt/official/feature/auth/utils/GoogleLoginManager.kt
  core/network/src/main/java/org/sopt/official/network/authenticator/CentralizeAuthenticator.kt
  core/network/src/main/java/org/sopt/official/network/interceptor/AuthInterceptor.kt
  data/auth/src/main/java/org/sopt/official/data/auth/remote/api/AuthApi.kt
  data/auth/src/main/java/org/sopt/official/data/auth/repository/DefaultAuthRepository.kt
  domain/auth/src/main/java/org/sopt/official/domain/auth/repository/AuthRepository.kt
Labels: size/M

#1278 [FEAT/#1277] 홈 플그영역에서 프로필 이동 기능 구현
  data/home/src/main/java/org/sopt/official/data/home/mapper/HomeMapper.kt
  data/home/src/main/java/org/sopt/official/data/home/remote/response/HomeLatestPostsResponseDto.kt
  data/home/src/main/java/org/sopt/official/data/home/remote/response/HomePopularPostsResponseDto.kt
  domain/home/src/main/java/org/sopt/official/domain/home/model/LatestPost.kt
  domain/home/src/main/java/org/sopt/official/domain/home/model/PopularPost.kt
  feature/home/src/main/java/org/sopt/official/feature/home/HomeRoute.kt
  feature/home/src/main/java/org/sopt/official/feature/home/component/HomeLatestNewsSection.kt
  feature/home/src/main/java/org/sopt/official/feature/home/component/HomePlaygroundPost.kt
  feature/home/src/main/java/org/sopt/official/feature/home/component/HomePopularNewsSection.kt
  feature/home/src/main/java/org/sopt/official/feature/home/mapper/HomeModelMapper.kt
  feature/home/src/main/java/org/sopt/official/feature/home/model/HomeUiState.kt
  feature/home/src/main/java/org/sopt/official/feature/home/navigation/HomeNavigation.kt
  feature/main/src/main/java/org/sopt/official/feature/main/MainScreen.kt
Labels: size/M

#1269 [FEAT/#1255] 강제 업데이트 만들어요
  app/build.gradle.kts
  app/src/main/java/org/sopt/official/feature/auth/AuthActivity.kt
  app/src/main/java/org/sopt/official/feature/auth/AuthViewModel.kt
  app/src/main/java/org/sopt/official/feature/auth/component/UpdateDialog.kt
  core/common/build.gradle.kts
  core/common/src/main/java/org/sopt/official/common/config/remoteconfig/RemoteConfigModule.kt
  core/common/src/main/java/org/sopt/official/common/config/remoteconfig/SoptRemoteConfig.kt
  core/common/src/main/java/org/sopt/official/common/config/remoteconfig/SoptRemoteConfigImpl.kt
  core/common/src/main/java/org/sopt/official/common/config/remoteconfig/UpdateConfigModel.kt
  core/common/src/main/java/org/sopt/official/common/di/JsonModule.kt
  core/common/src/main/java/org/sopt/official/common/util/ContextExt.kt
  core/designsystem/src/main/java/org/sopt/official/designsystem/component/dialog/OneButtonDialog.kt
  core/designsystem/src/main/java/org/sopt/official/designsystem/component/dialog/SoptBasicDialog.kt
  core/designsystem/src/main/java/org/sopt/official/designsystem/component/dialog/TwoButtonDialog.kt
  core/network/src/main/java/org/sopt/official/network/di/NetModule.kt
  gradle/libs.versions.toml
Labels: size/XL
