Repository sopt-makers/sopt-android, pull requests merged in 2025-03, with the labels that each got.

#1105 Revert "fix(deps): update compose.destination to v2 (major)"
  gradle/libs.versions.toml
Labels: size/XS

#1112 [FIX/#1100] FCM토큰 등록 과정에서 직렬화 문제를 수정합니다.
  data/notification/src/main/java/org/sopt/official/data/notification/model/request/UpdatePushTokenRequest.kt
  data/notification/src/main/java/org/sopt/official/data/notification/model/response/UpdatePushTokenResponse.kt
Labels: size/XS

#1119 [FEAT/#1114] 알림뷰 수정 및 기타 QA 사항 반영
  data/notification/src/main/java/org/sopt/official/data/notification/repository/DefaultNotificationRepository.kt
  data/notification/src/main/java/org/sopt/official/data/notification/service/NotificationService.kt
  domain/notification/src/main/kotlin/org/sopt/official/domain/notification/repository/NotificationRepository.kt
  feature/notification/src/main/java/org/sopt/official/feature/notification/all/NotificationActivity.kt
  feature/notification/src/main/java/org/sopt/official/feature/notification/all/NotificationCategory.kt
  feature/notification/src/main/java/org/sopt/official/feature/notification/all/NotificationPagingSource.kt
  feature/notification/src/main/java/org/sopt/official/feature/notification/all/NotificationState.kt
  feature/notification/src/main/java/org/sopt/official/feature/notification/all/NotificationViewModel.kt
  feature/notification/src/main/java/org/sopt/official/feature/notification/all/component/NotificationCategoryChip.kt
  feature/notification/src/main/java/org/sopt/official/feature/notification/all/component/NotificationInfoItem.kt
  feature/notification/src/main/java/org/sopt/official/feature/notification/detail/NotificationDetailActivity.kt
  feature/notification/src/main/res/drawable/ic_arrow_left_24.xml
  feature/soptlog/src/main/java/org/sopt/official/feature/soptlog/SoptlogScreen.kt
  feature/soptlog/src/main/java/org/sopt/official/feature/soptlog/component/SoptlogDashboard.kt
Labels: size/XL

#1120 [MOD/#1113] 홈 앰플리튜드 추가와 아이콘 오류를 수정합니다
  core/analytics/src/main/java/org/sopt/official/analytics/impl/AmplitudeTracker.kt
  feature/fortune/src/main/java/org/sopt/official/feature/fortune/component/FortuneTopBar.kt
  feature/fortune/src/main/java/org/sopt/official/feature/fortune/feature/fortuneAmulet/FortuneAmuletScreen.kt
  feature/fortune/src/main/java/org/sopt/official/feature/fortune/feature/fortuneDetail/FortuneDetailRoute.kt
  feature/fortune/src/main/java/org/sopt/official/feature/fortune/feature/home/HomeScreen.kt
  feature/home/src/main/java/org/sopt/official/feature/home/HomeRoute.kt
  feature/home/src/main/java/org/sopt/official/feature/home/HomeUtils.kt
  feature/home/src/main/java/org/sopt/official/feature/home/NewHomeViewModel.kt
  feature/home/src/main/java/org/sopt/official/feature/home/component/HomeShortcutButtons.kt
  feature/home/src/main/java/org/sopt/official/feature/home/navigation/HomeUrl.kt
  feature/home/src/main/res/drawable/ic_file_text_filled.xml
  feature/home/src/main/res/drawable/ic_moim.xml
  feature/home/src/main/res/drawable/ic_pencil.xml
  feature/home/src/main/res/drawable/ic_project.xml
  feature/main/build.gradle.kts
  feature/main/src/main/java/org/sopt/official/feature/main/MainActivity.kt
  feature/main/src/main/java/org/sopt/official/feature/main/MainScreen.kt
  feature/main/src/main/java/org/sopt/official/feature/main/MainTab.kt
  feature/soptlog/build.gradle.kts
  feature/soptlog/src/main/java/org/sopt/official/feature/soptlog/SoptlogScreen.kt
Labels: size/L

#1124 [FIX/#1123] 콕찌르기 QA 반영
  feature/poke/src/main/java/org/sopt/official/feature/poke/main/PokeMainListAdapter.kt
  feature/poke/src/main/java/org/sopt/official/feature/poke/main/PokeMainViewHolder.kt
  feature/poke/src/main/java/org/sopt/official/feature/poke/notification/PokeNotificationActivity.kt
  feature/poke/src/main/java/org/sopt/official/feature/poke/notification/PokeNotificationViewModel.kt
  feature/schedule/src/main/java/org/sopt/official/feature/schedule/component/ScheduleItem.kt
Labels: size/M

#1125 [bump-libraries] 주요 라이브러리들 bump
  gradle/libs.versions.toml
Labels: size/S

#1129 [FIX/#1128] 1차 전체 QA 사항 반영
  feature/home/src/main/java/org/sopt/official/feature/home/HomeRoute.kt
  feature/home/src/main/java/org/sopt/official/feature/home/NewHomeViewModel.kt
  feature/main/src/main/java/org/sopt/official/feature/main/MainNavigator.kt
  feature/main/src/main/java/org/sopt/official/feature/main/MainScreen.kt
  feature/poke/src/main/java/org/sopt/official/feature/poke/friend/detail/FriendListDetailBottomSheetFragment.kt
  feature/poke/src/main/java/org/sopt/official/feature/poke/friend/summary/FriendListSummaryActivity.kt
  feature/poke/src/main/java/org/sopt/official/feature/poke/main/PokeMainActivity.kt
  feature/poke/src/main/java/org/sopt/official/feature/poke/notification/PokeNotificationActivity.kt
  feature/soptlog/src/main/java/org/sopt/official/feature/soptlog/SoptLogViewModel.kt
  feature/soptlog/src/main/java/org/sopt/official/feature/soptlog/SoptlogScreen.kt
Labels: size/L

#1130 [Fix/#1126] 1차 QA 사항 반영
  feature/home/src/main/java/org/sopt/official/feature/home/HomeRoute.kt
  feature/home/src/main/java/org/sopt/official/feature/home/NewHomeViewModel.kt
  feature/home/src/main/res/drawable/img_soptmadi.png
  feature/notification/src/main/java/org/sopt/official/feature/notification/all/NotificationActivity.kt
  feature/soptlog/build.gradle.kts
  feature/soptlog/src/main/java/org/sopt/official/feature/soptlog/SoptlogScreen.kt
  feature/soptlog/src/main/java/org/sopt/official/feature/soptlog/component/SoptlogDashboard.kt
  feature/soptlog/src/main/java/org/sopt/official/feature/soptlog/component/SoptlogProfile.kt
  feature/soptlog/src/main/res/drawable/ic_close_18.xml
  feature/soptlog/src/main/res/drawable/ic_helper.xml
  gradle/libs.versions.toml
Labels: size/L

#1134 [HOTFIX/#1133] allowBackup false로 수정
  app/src/main/AndroidManifest.xml
Labels: size/XS

#1136 [FIX/#1135] update home intent to main intent in SchemeActivity
  app/src/main/java/org/sopt/official/feature/navigator/NavigatorProviderIntent.kt
  app/src/main/java/org/sopt/official/feature/notification/SchemeActivity.kt
  core/common/src/main/java/org/sopt/official/common/navigator/DeepLinkType.kt
  core/common/src/main/java/org/sopt/official/common/navigator/NavigatorProvider.kt
Labels: size/M

#1138 [HOTFIX/#1137] bytearray 길이 검증
  core/security/src/main/java/org/sopt/official/security/util/CryptoExt.kt
Labels: size/S

#1140 [FEAT/#1139] 웹뷰 카카오 intent 처리 로직 구현
  core/webview/src/main/java/org/sopt/official/webview/view/SoptWebView.kt
  core/webview/src/main/java/org/sopt/official/webview/view/SoptWebViewClient.kt
  core/webview/src/main/java/org/sopt/official/webview/view/WebViewActivity.kt
  feature/home/src/main/java/org/sopt/official/feature/home/component/HomeShortcutButtons.kt
  feature/home/src/main/res/drawable/ic_instagram_40.xml
Labels: size/L
